//! Tests for tools/release_drift.zig, the release hook behind
//! `just check-release-drift`.
//!
//! The tool's git and file reads are glue; these tests drive its pure core:
//! the line diff, the bump classifier, the CHANGELOG reader and the rules
//! that turn drift into findings. The four "plan" tests replay the
//! ablations from docs/sprint-plan-2026-10-04.md item 3 on fixture text.

const std = @import("std");
const drift = @import("release-drift");
const testing = std.testing;

const gpa = testing.allocator;

fn version(text: []const u8) std.SemanticVersion {
    return std.SemanticVersion.parse(text) catch unreachable;
}

fn countKind(findings: []const drift.Finding, kind: drift.Kind) usize {
    var n: usize = 0;
    for (findings) |f| {
        if (f.kind == kind) n += 1;
    }
    return n;
}

fn failures(findings: []const drift.Finding) usize {
    var n: usize = 0;
    for (findings) |f| {
        if (drift.severity(f.kind) == .fail) n += 1;
    }
    return n;
}

/// One drift entry per snapshot file, from (old, new) text pairs. A null
/// old text means the file did not exist at the previous release.
const Pair = struct { old: ?[]const u8, new: []const u8 };

fn drifts(pairs: [drift.snapshots.len]Pair) ![drift.snapshots.len]drift.FileDrift {
    var out: [drift.snapshots.len]drift.FileDrift = undefined;
    for (drift.snapshots, pairs, 0..) |snapshot, pair, i| {
        out[i] = .{
            .path = snapshot.path,
            .tier = snapshot.tier,
            .absent_at_prev = pair.old == null,
            .diff = try drift.diffLines(gpa, pair.old orelse "", pair.new, 4),
        };
    }
    return out;
}

fn freeDrifts(list: []const drift.FileDrift) void {
    for (list) |d| d.diff.deinit(gpa);
}

const header = "# STABLE public API snapshot\n# Generated by a tool.\n";
const base_stable = header ++ "lib.a: fn () void\nlib.b: fn (u32) error{Bad}!void\nlib.c: struct\n";
const base_experimental = "# EXPERIMENTAL\nlib.x: fn () void\nlib.y: field u8\n";
const empty_changelog = "# Changelog\n\n## [Unreleased]\n\n## [0.19.1] - 2026-10-04\n\n### Security\n\n- A fix.\n";

/// The five files unchanged.
fn unchanged() [drift.snapshots.len]Pair {
    var out: [drift.snapshots.len]Pair = undefined;
    for (drift.snapshots, 0..) |snapshot, i| {
        const text = if (snapshot.tier == .stable) base_stable else base_experimental;
        out[i] = .{ .old = text, .new = text };
    }
    return out;
}

fn indexOf(path: []const u8) usize {
    for (drift.snapshots, 0..) |snapshot, i| {
        if (std.mem.eql(u8, snapshot.path, path)) return i;
    }
    unreachable;
}

// ---------------------------------------------------------------------------
// The snapshot table.
// ---------------------------------------------------------------------------

test "the hook reads the five snapshot files, two of them Stable" {
    try testing.expectEqual(@as(usize, 5), drift.snapshots.len);
    const expected = [_]struct { []const u8, drift.Tier }{
        .{ "docs/api-snapshot.txt", .stable },
        .{ "docs/generated-shape.txt", .stable },
        .{ "docs/api-snapshot-experimental.txt", .experimental },
        .{ "docs/api-snapshot-experimental-quic.txt", .experimental },
        .{ "docs/generated-shape-experimental.txt", .experimental },
    };
    for (expected) |e| {
        try testing.expectEqual(e[1], drift.snapshots[indexOf(e[0])].tier);
    }
}

// ---------------------------------------------------------------------------
// diffLines.
// ---------------------------------------------------------------------------

test "diffLines: identical text has no drift" {
    const d = try drift.diffLines(gpa, base_stable, base_stable, 4);
    defer d.deinit(gpa);
    try testing.expectEqual(@as(usize, 0), d.added);
    try testing.expectEqual(@as(usize, 0), d.removed);
}

test "diffLines: a changed line is one removal and one addition" {
    const new = header ++ "lib.a: fn () void\nlib.b: fn (u32) error{Bad,Worse}!void\nlib.c: struct\n";
    const d = try drift.diffLines(gpa, base_stable, new, 4);
    defer d.deinit(gpa);
    try testing.expectEqual(@as(usize, 1), d.added);
    try testing.expectEqual(@as(usize, 1), d.removed);
    try testing.expectEqual(@as(usize, 1), d.removed_sample.len);
    try testing.expectEqualStrings("lib.b: fn (u32) error{Bad}!void", d.removed_sample[0]);
}

test "diffLines: header comments and blank lines are not surface" {
    const new = "# A rewritten header.\n\nlib.a: fn () void\n\nlib.b: fn (u32) error{Bad}!void\nlib.c: struct\n# trailer\n";
    const d = try drift.diffLines(gpa, base_stable, new, 4);
    defer d.deinit(gpa);
    try testing.expectEqual(@as(usize, 0), d.added);
    try testing.expectEqual(@as(usize, 0), d.removed);
}

test "diffLines: CRLF line ends match LF ones" {
    const new = "# STABLE public API snapshot\r\nlib.a: fn () void\r\nlib.b: fn (u32) error{Bad}!void\r\nlib.c: struct\r\n";
    const d = try drift.diffLines(gpa, base_stable, new, 4);
    defer d.deinit(gpa);
    try testing.expectEqual(@as(usize, 0), d.added);
    try testing.expectEqual(@as(usize, 0), d.removed);
}

test "diffLines: lines are a multiset and order does not matter" {
    const removed_dup = try drift.diffLines(gpa, "a\nb\nb\nc\n", "c\nb\na\n", 4);
    defer removed_dup.deinit(gpa);
    try testing.expectEqual(@as(usize, 0), removed_dup.added);
    try testing.expectEqual(@as(usize, 1), removed_dup.removed);

    // A duplicated line in the new text is an addition, too.
    const added_dup = try drift.diffLines(gpa, "a\nb\n", "b\na\nb\n", 4);
    defer added_dup.deinit(gpa);
    try testing.expectEqual(@as(usize, 1), added_dup.added);
    try testing.expectEqual(@as(usize, 0), added_dup.removed);
}

test "diffLines: a file new at this release is all additions" {
    const d = try drift.diffLines(gpa, "", base_stable, 4);
    defer d.deinit(gpa);
    try testing.expectEqual(@as(usize, 3), d.added);
    try testing.expectEqual(@as(usize, 0), d.removed);
}

test "diffLines: the removed sample keeps file order and stops at the limit" {
    const old = "r1\nkeep\nr2\nr3\n";
    const d = try drift.diffLines(gpa, old, "keep\n", 2);
    defer d.deinit(gpa);
    try testing.expectEqual(@as(usize, 3), d.removed);
    try testing.expectEqual(@as(usize, 2), d.removed_sample.len);
    try testing.expectEqualStrings("r1", d.removed_sample[0]);
    try testing.expectEqualStrings("r2", d.removed_sample[1]);
}

// ---------------------------------------------------------------------------
// classifyBump and the version reader.
// ---------------------------------------------------------------------------

test "classifyBump: none, patch, minor, major" {
    try testing.expectEqual(drift.Bump.none, try drift.classifyBump(version("0.19.1"), version("0.19.1")));
    try testing.expectEqual(drift.Bump.patch, try drift.classifyBump(version("0.19.1"), version("0.19.2")));
    try testing.expectEqual(drift.Bump.minor, try drift.classifyBump(version("0.19.1"), version("0.20.0")));
    // A minor bump that does not reset the patch is still a minor bump.
    try testing.expectEqual(drift.Bump.minor, try drift.classifyBump(version("0.19.1"), version("0.20.3")));
    try testing.expectEqual(drift.Bump.major, try drift.classifyBump(version("0.19.1"), version("1.0.0")));
}

test "classifyBump: a version that goes backwards is an error" {
    try testing.expectError(error.VersionWentBackwards, drift.classifyBump(version("0.19.1"), version("0.19.0")));
    try testing.expectError(error.VersionWentBackwards, drift.classifyBump(version("0.19.1"), version("0.18.9")));
    try testing.expectError(error.VersionWentBackwards, drift.classifyBump(version("1.0.0"), version("0.99.0")));
}

test "zonVersion reads the manifest's .version" {
    const zon =
        \\.{
        \\    .name = .capnpc_zig,
        \\    .version = "0.19.1",
        \\    .minimum_zig_version = "0.17.0",
        \\}
    ;
    try testing.expectEqualStrings("0.19.1", drift.zonVersion(zon).?);
    try testing.expectEqual(@as(?[]const u8, null), drift.zonVersion(".{ .name = .x }"));
}

// ---------------------------------------------------------------------------
// readChangelog.
// ---------------------------------------------------------------------------

const changelog_with_release =
    \\# Changelog
    \\
    \\## [Unreleased]
    \\
    \\## [0.20.0] - 2026-10-18
    \\
    \\### Breaking
    \\
    \\- **`events.Source` gains `.unix` (Experimental).**
    \\  - **Migration:** add an `else` arm.
    \\
    \\### Added
    \\
    \\- Something.
    \\
    \\## [0.19.1] - 2026-10-04
    \\
    \\### Security
    \\
    \\- A fix.
    \\
    \\[Unreleased]: https://example.invalid/compare/v0.20.0...HEAD
    \\
;

test "readChangelog: the version's own section wins over [Unreleased]" {
    const c = drift.readChangelog(changelog_with_release, "0.20.0");
    try testing.expectEqualStrings("0.20.0", c.section);
    try testing.expect(c.found);
    try testing.expect(c.breaking);
    try testing.expect(c.breaking_experimental);
    try testing.expect(c.breaking_migration);
}

test "readChangelog: a version with no section falls back to [Unreleased]" {
    const c = drift.readChangelog(changelog_with_release, "0.21.0");
    try testing.expectEqualStrings("Unreleased", c.section);
    try testing.expect(c.found);
    // The Breaking heading of the 0.20.0 section below does not count.
    try testing.expect(!c.breaking);
}

test "readChangelog: no version reads [Unreleased]" {
    const c = drift.readChangelog(changelog_with_release, null);
    try testing.expectEqualStrings("Unreleased", c.section);
    try testing.expect(!c.breaking);
}

test "readChangelog: Breaking stops at the next ### heading" {
    const text =
        \\## [Unreleased]
        \\
        \\### Breaking
        \\
        \\- A Stable rename.
        \\
        \\### Added
        \\
        \\- An Experimental thing. Migration notes are elsewhere.
        \\
    ;
    const c = drift.readChangelog(text, null);
    try testing.expect(c.breaking);
    try testing.expect(!c.breaking_experimental);
    try testing.expect(!c.breaking_migration);
}

test "readChangelog: an empty Breaking heading is no Breaking entry" {
    const c = drift.readChangelog("## [Unreleased]\n\n### Breaking\n\n### Added\n\n- x\n", null);
    try testing.expect(c.found);
    try testing.expect(!c.breaking);
}

test "readChangelog: a missing section is reported" {
    const c = drift.readChangelog("# Changelog\n\n## [0.19.1] - 2026-10-04\n", null);
    try testing.expect(!c.found);
    try testing.expect(!c.breaking);
}

test "readChangelog: a heading the version is only a prefix of does not match" {
    // A request for 0.20.0 must skip `## [0.20.0-rc.1]` (whose Breaking
    // entry is not this release's) and read `## [0.20.0]`.
    const text =
        \\## [Unreleased]
        \\
        \\## [0.20.0-rc.1] - x
        \\
        \\### Breaking
        \\
        \\- b
        \\
        \\## [0.20.0] - y
        \\
        \\### Added
        \\
        \\- a
        \\
    ;
    const c = drift.readChangelog(text, "0.20.0");
    try testing.expectEqualStrings("0.20.0", c.section);
    try testing.expect(c.found);
    try testing.expect(!c.breaking);
}

// ---------------------------------------------------------------------------
// evaluate: the plan's four ablations, on fixture text.
// ---------------------------------------------------------------------------

test "plan ablation 1: editing one Stable line without a Breaking entry is red" {
    var pairs = unchanged();
    pairs[indexOf("docs/generated-shape.txt")].new = header ++ "lib.a: fn () void\nlib.b: fn (u64) error{Bad}!void\nlib.c: struct\n";
    const list = try drifts(pairs);
    defer freeDrifts(&list);
    const findings = try drift.evaluate(gpa, .minor, &list, drift.readChangelog(empty_changelog, "0.20.0"));
    defer gpa.free(findings);
    try testing.expectEqual(@as(usize, 1), countKind(findings, .stable_removal_without_breaking));
    try testing.expectEqualStrings("docs/generated-shape.txt", findings[0].path.?);
    try testing.expectEqual(@as(usize, 1), failures(findings));
}

test "plan ablation 2: adding one line only, with a minor bump, is green" {
    var pairs = unchanged();
    pairs[indexOf("docs/generated-shape.txt")].new = base_stable ++ "lib.d: fn () void\n";
    const list = try drifts(pairs);
    defer freeDrifts(&list);
    const findings = try drift.evaluate(gpa, .minor, &list, drift.readChangelog(empty_changelog, "0.20.0"));
    defer gpa.free(findings);
    try testing.expectEqual(@as(usize, 0), failures(findings));
    try testing.expectEqual(@as(usize, 0), findings.len);
}

test "plan ablation 3: a patch bump with an added line is red" {
    var pairs = unchanged();
    pairs[indexOf("docs/api-snapshot.txt")].new = base_stable ++ "lib.d: fn () void\n";
    const list = try drifts(pairs);
    defer freeDrifts(&list);
    const findings = try drift.evaluate(gpa, .patch, &list, drift.readChangelog(empty_changelog, "0.19.2"));
    defer gpa.free(findings);
    try testing.expectEqual(@as(usize, 1), countKind(findings, .patch_with_drift));
    try testing.expectEqual(@as(usize, 1), failures(findings));
}

test "plan ablation 4: a patch bump with an Experimental-only change is red" {
    var pairs = unchanged();
    pairs[indexOf("docs/api-snapshot-experimental-quic.txt")].new = base_experimental ++ "lib.z: fn () void\n";
    const list = try drifts(pairs);
    defer freeDrifts(&list);
    const findings = try drift.evaluate(gpa, .patch, &list, drift.readChangelog(empty_changelog, "0.19.2"));
    defer gpa.free(findings);
    try testing.expectEqual(@as(usize, 1), countKind(findings, .patch_with_drift));
    try testing.expectEqual(@as(usize, 1), failures(findings));
}

// ---------------------------------------------------------------------------
// evaluate: the other rules.
// ---------------------------------------------------------------------------

test "a Stable removal with a Breaking entry and a minor bump is green" {
    var pairs = unchanged();
    pairs[indexOf("docs/api-snapshot.txt")].new = header ++ "lib.a: fn () void\nlib.c: struct\n";
    const list = try drifts(pairs);
    defer freeDrifts(&list);
    const findings = try drift.evaluate(gpa, .minor, &list, drift.readChangelog(changelog_with_release, "0.20.0"));
    defer gpa.free(findings);
    try testing.expectEqual(@as(usize, 0), findings.len);
}

test "a Stable removal is red under a patch bump even with a Breaking entry" {
    var pairs = unchanged();
    pairs[indexOf("docs/api-snapshot.txt")].new = header ++ "lib.a: fn () void\nlib.c: struct\n";
    const list = try drifts(pairs);
    defer freeDrifts(&list);
    const findings = try drift.evaluate(gpa, .patch, &list, drift.readChangelog(changelog_with_release, "0.20.0"));
    defer gpa.free(findings);
    try testing.expectEqual(@as(usize, 0), countKind(findings, .stable_removal_without_breaking));
    try testing.expectEqual(@as(usize, 1), countKind(findings, .patch_with_drift));
}

test "each Stable file is checked on its own" {
    var pairs = unchanged();
    pairs[indexOf("docs/api-snapshot.txt")].new = header ++ "lib.a: fn () void\n";
    pairs[indexOf("docs/generated-shape.txt")].new = header ++ "lib.a: fn () void\n";
    const list = try drifts(pairs);
    defer freeDrifts(&list);
    const findings = try drift.evaluate(gpa, .minor, &list, drift.readChangelog(empty_changelog, null));
    defer gpa.free(findings);
    try testing.expectEqual(@as(usize, 2), countKind(findings, .stable_removal_without_breaking));
}

test "an Experimental removal without a Breaking (Experimental) entry warns, and does not fail" {
    var pairs = unchanged();
    pairs[indexOf("docs/generated-shape-experimental.txt")].new = "# EXPERIMENTAL\nlib.x: fn () void\n";
    const list = try drifts(pairs);
    defer freeDrifts(&list);
    const findings = try drift.evaluate(gpa, .minor, &list, drift.readChangelog(empty_changelog, "0.20.0"));
    defer gpa.free(findings);
    try testing.expectEqual(@as(usize, 1), countKind(findings, .experimental_removal_without_breaking_entry));
    try testing.expectEqual(drift.Severity.warn, drift.severity(.experimental_removal_without_breaking_entry));
    try testing.expectEqual(@as(usize, 0), failures(findings));
}

test "an Experimental removal under a Breaking (Experimental) entry is quiet" {
    var pairs = unchanged();
    pairs[indexOf("docs/api-snapshot-experimental.txt")].new = "# EXPERIMENTAL\nlib.x: fn () void\n";
    const list = try drifts(pairs);
    defer freeDrifts(&list);
    const findings = try drift.evaluate(gpa, .minor, &list, drift.readChangelog(changelog_with_release, "0.20.0"));
    defer gpa.free(findings);
    try testing.expectEqual(@as(usize, 0), findings.len);
}

test "a Stable file new at this release counts as additions only" {
    var pairs = unchanged();
    pairs[indexOf("docs/generated-shape.txt")] = .{ .old = null, .new = base_stable };
    pairs[indexOf("docs/generated-shape-experimental.txt")] = .{ .old = null, .new = base_experimental };
    const list = try drifts(pairs);
    defer freeDrifts(&list);
    try testing.expect(list[indexOf("docs/generated-shape.txt")].absent_at_prev);
    try testing.expectEqual(@as(usize, 3), list[indexOf("docs/generated-shape.txt")].diff.added);

    const minor = try drift.evaluate(gpa, .minor, &list, drift.readChangelog(empty_changelog, "0.20.0"));
    defer gpa.free(minor);
    try testing.expectEqual(@as(usize, 0), minor.len);

    const patch = try drift.evaluate(gpa, .patch, &list, drift.readChangelog(empty_changelog, "0.19.2"));
    defer gpa.free(patch);
    try testing.expectEqual(@as(usize, 1), countKind(patch, .patch_with_drift));
}

test "no drift under a patch bump is green" {
    const list = try drifts(unchanged());
    defer freeDrifts(&list);
    const findings = try drift.evaluate(gpa, .patch, &list, drift.readChangelog(empty_changelog, "0.19.2"));
    defer gpa.free(findings);
    try testing.expectEqual(@as(usize, 0), findings.len);
}

test "an unbumped version with drift is a note, not a failure" {
    var pairs = unchanged();
    pairs[indexOf("docs/api-snapshot-experimental.txt")].new = base_experimental ++ "lib.z: fn () void\n";
    const list = try drifts(pairs);
    defer freeDrifts(&list);
    const findings = try drift.evaluate(gpa, .none, &list, drift.readChangelog(empty_changelog, null));
    defer gpa.free(findings);
    try testing.expectEqual(@as(usize, 1), countKind(findings, .bump_pending));
    try testing.expectEqual(drift.Severity.note, drift.severity(.bump_pending));
    try testing.expectEqual(@as(usize, 0), failures(findings));
}

test "an unbumped version still fails a Stable removal with no Breaking entry" {
    var pairs = unchanged();
    pairs[indexOf("docs/api-snapshot.txt")].new = header ++ "lib.a: fn () void\nlib.c: struct\n";
    const list = try drifts(pairs);
    defer freeDrifts(&list);
    const findings = try drift.evaluate(gpa, .none, &list, drift.readChangelog(empty_changelog, null));
    defer gpa.free(findings);
    try testing.expectEqual(@as(usize, 1), countKind(findings, .stable_removal_without_breaking));
    try testing.expectEqual(@as(usize, 1), failures(findings));
}

test "a Breaking section with no Migration paragraph warns" {
    const text = "## [Unreleased]\n\n### Breaking\n\n- A Stable rename.\n";
    const list = try drifts(unchanged());
    defer freeDrifts(&list);
    const findings = try drift.evaluate(gpa, .minor, &list, drift.readChangelog(text, null));
    defer gpa.free(findings);
    try testing.expectEqual(@as(usize, 1), countKind(findings, .breaking_without_migration));
    try testing.expectEqual(drift.Severity.warn, drift.severity(.breaking_without_migration));
}

test "a missing CHANGELOG section warns" {
    const list = try drifts(unchanged());
    defer freeDrifts(&list);
    const findings = try drift.evaluate(gpa, .minor, &list, drift.readChangelog("# Changelog\n", "0.20.0"));
    defer gpa.free(findings);
    try testing.expectEqual(@as(usize, 1), countKind(findings, .changelog_section_missing));
    try testing.expectEqual(drift.Severity.warn, drift.severity(.changelog_section_missing));
}
