// Generated by capnpc-zig
// Source: examples/kvstore/kvstore.capnp

const std = @import("std");
const capnpc = @import("capnpc-zig");
const message = capnpc.message;
const schema = capnpc.schema;
const rpc = capnpc.rpc;

pub const CAPNP_SCHEMA_MANIFEST_JSON: []const u8 = "{\"schema\":\"examples/kvstore/kvstore.capnp\",\"module\":\"kvstore\",\"serde\":[{\"id\":15550500692302571658,\"type_name\":\"DeleteParams\",\"to_json_export\":\"capnp_kvstore_delete_params_to_json\",\"from_json_export\":\"capnp_kvstore_delete_params_from_json\"},{\"id\":14000907210868832632,\"type_name\":\"DeleteResults\",\"to_json_export\":\"capnp_kvstore_delete_results_to_json\",\"from_json_export\":\"capnp_kvstore_delete_results_from_json\"},{\"id\":12392355825827701191,\"type_name\":\"Entry\",\"to_json_export\":\"capnp_kvstore_entry_to_json\",\"from_json_export\":\"capnp_kvstore_entry_from_json\"},{\"id\":17767598820233916730,\"type_name\":\"GetParams\",\"to_json_export\":\"capnp_kvstore_get_params_to_json\",\"from_json_export\":\"capnp_kvstore_get_params_from_json\"},{\"id\":13421522526614393234,\"type_name\":\"GetResults\",\"to_json_export\":\"capnp_kvstore_get_results_to_json\",\"from_json_export\":\"capnp_kvstore_get_results_from_json\"},{\"id\":16657142347263246436,\"type_name\":\"ListParams\",\"to_json_export\":\"capnp_kvstore_list_params_to_json\",\"from_json_export\":\"capnp_kvstore_list_params_from_json\"},{\"id\":11733688047753984483,\"type_name\":\"ListResults\",\"to_json_export\":\"capnp_kvstore_list_results_to_json\",\"from_json_export\":\"capnp_kvstore_list_results_from_json\"},{\"id\":11680591861407114620,\"type_name\":\"SetParams\",\"to_json_export\":\"capnp_kvstore_set_params_to_json\",\"from_json_export\":\"capnp_kvstore_set_params_from_json\"},{\"id\":14079650963604611870,\"type_name\":\"SetResults\",\"to_json_export\":\"capnp_kvstore_set_results_to_json\",\"from_json_export\":\"capnp_kvstore_set_results_from_json\"}]}";
pub fn capnpSchemaManifestJson() []const u8 {
    return CAPNP_SCHEMA_MANIFEST_JSON;
}

pub const Entry = struct {
    fn EnumListReader(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !EnumType {
                return std.meta.intToEnum(EnumType, try self._list.get(index)) catch return error.InvalidEnumValue;
            }

            pub fn raw(self: @This()) message.U16ListReader {
                return self._list;
            }
        };
    }

    fn EnumListBuilder(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn set(self: @This(), index: u32, value: EnumType) !void {
                try self._list.set(index, @intFromEnum(value));
            }

            pub fn raw(self: @This()) message.U16ListBuilder {
                return self._list;
            }
        };
    }

    fn StructListReader(comptime StructType: type) type {
        return struct {
            _list: message.StructListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Reader {
                const item = try self._list.get(index);
                return StructType.Reader.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListReader {
                return self._list;
            }
        };
    }

    fn StructListBuilder(comptime StructType: type) type {
        return struct {
            _list: message.StructListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Builder {
                const item = try self._list.get(index);
                return StructType.Builder.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListBuilder {
                return self._list;
            }
        };
    }

    const DataListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) ![]const u8 {
            return try self._list.getData(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const DataListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, value: []const u8) !void {
            try self._list.setData(index, value);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    const CapabilityListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) !message.Capability {
            return try self._list.getCapability(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const CapabilityListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, cap: message.Capability) !void {
            try self._list.setCapability(index, cap);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn getKey(self: Reader) ![]const u8 {
            if (self._reader.isPointerNull(0)) return "";
            return try self._reader.readText(0);
        }

        pub fn getValue(self: Reader) ![]const u8 {
            if (self._reader.isPointerNull(1)) return &[_]u8{};
            return try self._reader.readData(1);
        }

        pub fn getVersion(self: Reader) !u64 {
            const raw = self._reader.readU64(0);
            const value = raw ^ @as(u64, 0);
            return value;
        }
    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(1, 2);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn setKey(self: *Builder, value: []const u8) !void {
            try self._builder.writeText(0, value);
        }

        pub fn setValue(self: *Builder, value: []const u8) !void {
            try self._builder.writeData(1, value);
        }

        pub fn setVersion(self: *Builder, value: u64) !void {
            const stored = @as(u64, @bitCast(value)) ^ @as(u64, 0);
            self._builder.writeU64(0, stored);
        }
    };
};

pub const KvStore = struct {
    pub const interface_id: u64 = 0xdabb8fabf7a284bf;
    pub const Method = enum(u16) {
        Get = 0,
        Set = 1,
        Delete = 2,
        List = 3,
    };

    pub const Get = struct {
        pub const ordinal: u16 = 0;
        pub const Params = GetParams;
        pub const Results = GetResults;
        pub const BuildFn = *const fn (ctx: *anyopaque, params: *Params.Builder) anyerror!void;
        pub const Handler = *const fn (ctx: *anyopaque, peer: *rpc.peer.Peer, params: Params.Reader, results: *Results.Builder, caps: *const rpc.cap_table.InboundCapTable) anyerror!void;
        pub const Response = union(enum) {
            results: Results.Reader,
            exception: rpc.protocol.Exception,
            canceled,
            results_sent_elsewhere,
            take_from_other_question: u32,
            accept_from_third_party,
        };
        pub const Callback = *const fn (ctx: *anyopaque, peer: *rpc.peer.Peer, response: Response, caps: *const rpc.cap_table.InboundCapTable) anyerror!void;

        const CallContext = struct {
            user_ctx: *anyopaque,
            build: ?BuildFn,
            callback: Callback,
        };

        const ReturnContext = struct {
            server: *Server,
            peer: *rpc.peer.Peer,
            params: Params.Reader,
            caps: *const rpc.cap_table.InboundCapTable,
        };

        fn callBuild(ctx_ptr: *anyopaque, call: *rpc.protocol.CallBuilder) anyerror!void {
            const ctx: *CallContext = @ptrCast(@alignCast(ctx_ptr));
            const params_builder = try call.initParamsStruct(0, 1);
            var params = Params.Builder.wrap(params_builder);
            if (ctx.build) |build_fn| {
                try build_fn(ctx.user_ctx, &params);
            }
            try call.setEmptyCapTable();
        }

        fn callReturn(ctx_ptr: *anyopaque, peer: *rpc.peer.Peer, ret: rpc.protocol.Return, caps: *const rpc.cap_table.InboundCapTable) anyerror!void {
            const ctx: *CallContext = @ptrCast(@alignCast(ctx_ptr));
            defer peer.allocator.destroy(ctx);
            var response: Response = undefined;
            switch (ret.tag) {
                .results => {
                    const payload = ret.results orelse return error.MissingReturnPayload;
                    const struct_reader = try payload.content.getStruct();
                    const results = Results.Reader.wrap(struct_reader);
                    response = .{ .results = results };
                },
                .exception => {
                    const ex = ret.exception orelse return error.MissingException;
                    response = .{ .exception = ex };
                },
                .canceled => response = .canceled,
                .results_sent_elsewhere => response = .results_sent_elsewhere,
                .take_from_other_question => {
                    const qid = ret.take_from_other_question orelse return error.MissingQuestionId;
                    response = .{ .take_from_other_question = qid };
                },
                .accept_from_third_party => response = .accept_from_third_party,
            }
            try ctx.callback(ctx.user_ctx, peer, response, caps);
        }

        fn handleCall(server: *Server, peer: *rpc.peer.Peer, call: rpc.protocol.Call, caps: *const rpc.cap_table.InboundCapTable) anyerror!void {
            const params_struct = try call.params.content.getStruct();
            const params = Params.Reader.wrap(params_struct);
            var ctx = ReturnContext{
                .server = server,
                .peer = peer,
                .params = params,
                .caps = caps,
            };
            try peer.sendReturnResults(call.question_id, &ctx, buildReturn);
        }

        fn buildReturn(ctx_ptr: *anyopaque, ret: *rpc.protocol.ReturnBuilder) anyerror!void {
            const ctx: *ReturnContext = @ptrCast(@alignCast(ctx_ptr));
            const results_builder = try ret.initResultsStruct(1, 1);
            var results = Results.Builder.wrap(results_builder);
            try ctx.server.vtable.get(ctx.server.ctx, ctx.peer, ctx.params, &results, ctx.caps);
            try ret.setEmptyCapTable();
        }
    };

    pub const Set = struct {
        pub const ordinal: u16 = 1;
        pub const Params = SetParams;
        pub const Results = SetResults;
        pub const BuildFn = *const fn (ctx: *anyopaque, params: *Params.Builder) anyerror!void;
        pub const Handler = *const fn (ctx: *anyopaque, peer: *rpc.peer.Peer, params: Params.Reader, results: *Results.Builder, caps: *const rpc.cap_table.InboundCapTable) anyerror!void;
        pub const Response = union(enum) {
            results: Results.Reader,
            exception: rpc.protocol.Exception,
            canceled,
            results_sent_elsewhere,
            take_from_other_question: u32,
            accept_from_third_party,
        };
        pub const Callback = *const fn (ctx: *anyopaque, peer: *rpc.peer.Peer, response: Response, caps: *const rpc.cap_table.InboundCapTable) anyerror!void;

        const CallContext = struct {
            user_ctx: *anyopaque,
            build: ?BuildFn,
            callback: Callback,
        };

        const ReturnContext = struct {
            server: *Server,
            peer: *rpc.peer.Peer,
            params: Params.Reader,
            caps: *const rpc.cap_table.InboundCapTable,
        };

        fn callBuild(ctx_ptr: *anyopaque, call: *rpc.protocol.CallBuilder) anyerror!void {
            const ctx: *CallContext = @ptrCast(@alignCast(ctx_ptr));
            const params_builder = try call.initParamsStruct(0, 2);
            var params = Params.Builder.wrap(params_builder);
            if (ctx.build) |build_fn| {
                try build_fn(ctx.user_ctx, &params);
            }
            try call.setEmptyCapTable();
        }

        fn callReturn(ctx_ptr: *anyopaque, peer: *rpc.peer.Peer, ret: rpc.protocol.Return, caps: *const rpc.cap_table.InboundCapTable) anyerror!void {
            const ctx: *CallContext = @ptrCast(@alignCast(ctx_ptr));
            defer peer.allocator.destroy(ctx);
            var response: Response = undefined;
            switch (ret.tag) {
                .results => {
                    const payload = ret.results orelse return error.MissingReturnPayload;
                    const struct_reader = try payload.content.getStruct();
                    const results = Results.Reader.wrap(struct_reader);
                    response = .{ .results = results };
                },
                .exception => {
                    const ex = ret.exception orelse return error.MissingException;
                    response = .{ .exception = ex };
                },
                .canceled => response = .canceled,
                .results_sent_elsewhere => response = .results_sent_elsewhere,
                .take_from_other_question => {
                    const qid = ret.take_from_other_question orelse return error.MissingQuestionId;
                    response = .{ .take_from_other_question = qid };
                },
                .accept_from_third_party => response = .accept_from_third_party,
            }
            try ctx.callback(ctx.user_ctx, peer, response, caps);
        }

        fn handleCall(server: *Server, peer: *rpc.peer.Peer, call: rpc.protocol.Call, caps: *const rpc.cap_table.InboundCapTable) anyerror!void {
            const params_struct = try call.params.content.getStruct();
            const params = Params.Reader.wrap(params_struct);
            var ctx = ReturnContext{
                .server = server,
                .peer = peer,
                .params = params,
                .caps = caps,
            };
            try peer.sendReturnResults(call.question_id, &ctx, buildReturn);
        }

        fn buildReturn(ctx_ptr: *anyopaque, ret: *rpc.protocol.ReturnBuilder) anyerror!void {
            const ctx: *ReturnContext = @ptrCast(@alignCast(ctx_ptr));
            const results_builder = try ret.initResultsStruct(0, 1);
            var results = Results.Builder.wrap(results_builder);
            try ctx.server.vtable.set(ctx.server.ctx, ctx.peer, ctx.params, &results, ctx.caps);
            try ret.setEmptyCapTable();
        }
    };

    pub const Delete = struct {
        pub const ordinal: u16 = 2;
        pub const Params = DeleteParams;
        pub const Results = DeleteResults;
        pub const BuildFn = *const fn (ctx: *anyopaque, params: *Params.Builder) anyerror!void;
        pub const Handler = *const fn (ctx: *anyopaque, peer: *rpc.peer.Peer, params: Params.Reader, results: *Results.Builder, caps: *const rpc.cap_table.InboundCapTable) anyerror!void;
        pub const Response = union(enum) {
            results: Results.Reader,
            exception: rpc.protocol.Exception,
            canceled,
            results_sent_elsewhere,
            take_from_other_question: u32,
            accept_from_third_party,
        };
        pub const Callback = *const fn (ctx: *anyopaque, peer: *rpc.peer.Peer, response: Response, caps: *const rpc.cap_table.InboundCapTable) anyerror!void;

        const CallContext = struct {
            user_ctx: *anyopaque,
            build: ?BuildFn,
            callback: Callback,
        };

        const ReturnContext = struct {
            server: *Server,
            peer: *rpc.peer.Peer,
            params: Params.Reader,
            caps: *const rpc.cap_table.InboundCapTable,
        };

        fn callBuild(ctx_ptr: *anyopaque, call: *rpc.protocol.CallBuilder) anyerror!void {
            const ctx: *CallContext = @ptrCast(@alignCast(ctx_ptr));
            const params_builder = try call.initParamsStruct(0, 1);
            var params = Params.Builder.wrap(params_builder);
            if (ctx.build) |build_fn| {
                try build_fn(ctx.user_ctx, &params);
            }
            try call.setEmptyCapTable();
        }

        fn callReturn(ctx_ptr: *anyopaque, peer: *rpc.peer.Peer, ret: rpc.protocol.Return, caps: *const rpc.cap_table.InboundCapTable) anyerror!void {
            const ctx: *CallContext = @ptrCast(@alignCast(ctx_ptr));
            defer peer.allocator.destroy(ctx);
            var response: Response = undefined;
            switch (ret.tag) {
                .results => {
                    const payload = ret.results orelse return error.MissingReturnPayload;
                    const struct_reader = try payload.content.getStruct();
                    const results = Results.Reader.wrap(struct_reader);
                    response = .{ .results = results };
                },
                .exception => {
                    const ex = ret.exception orelse return error.MissingException;
                    response = .{ .exception = ex };
                },
                .canceled => response = .canceled,
                .results_sent_elsewhere => response = .results_sent_elsewhere,
                .take_from_other_question => {
                    const qid = ret.take_from_other_question orelse return error.MissingQuestionId;
                    response = .{ .take_from_other_question = qid };
                },
                .accept_from_third_party => response = .accept_from_third_party,
            }
            try ctx.callback(ctx.user_ctx, peer, response, caps);
        }

        fn handleCall(server: *Server, peer: *rpc.peer.Peer, call: rpc.protocol.Call, caps: *const rpc.cap_table.InboundCapTable) anyerror!void {
            const params_struct = try call.params.content.getStruct();
            const params = Params.Reader.wrap(params_struct);
            var ctx = ReturnContext{
                .server = server,
                .peer = peer,
                .params = params,
                .caps = caps,
            };
            try peer.sendReturnResults(call.question_id, &ctx, buildReturn);
        }

        fn buildReturn(ctx_ptr: *anyopaque, ret: *rpc.protocol.ReturnBuilder) anyerror!void {
            const ctx: *ReturnContext = @ptrCast(@alignCast(ctx_ptr));
            const results_builder = try ret.initResultsStruct(1, 0);
            var results = Results.Builder.wrap(results_builder);
            try ctx.server.vtable.delete(ctx.server.ctx, ctx.peer, ctx.params, &results, ctx.caps);
            try ret.setEmptyCapTable();
        }
    };

    pub const List = struct {
        pub const ordinal: u16 = 3;
        pub const Params = ListParams;
        pub const Results = ListResults;
        pub const BuildFn = *const fn (ctx: *anyopaque, params: *Params.Builder) anyerror!void;
        pub const Handler = *const fn (ctx: *anyopaque, peer: *rpc.peer.Peer, params: Params.Reader, results: *Results.Builder, caps: *const rpc.cap_table.InboundCapTable) anyerror!void;
        pub const Response = union(enum) {
            results: Results.Reader,
            exception: rpc.protocol.Exception,
            canceled,
            results_sent_elsewhere,
            take_from_other_question: u32,
            accept_from_third_party,
        };
        pub const Callback = *const fn (ctx: *anyopaque, peer: *rpc.peer.Peer, response: Response, caps: *const rpc.cap_table.InboundCapTable) anyerror!void;

        const CallContext = struct {
            user_ctx: *anyopaque,
            build: ?BuildFn,
            callback: Callback,
        };

        const ReturnContext = struct {
            server: *Server,
            peer: *rpc.peer.Peer,
            params: Params.Reader,
            caps: *const rpc.cap_table.InboundCapTable,
        };

        fn callBuild(ctx_ptr: *anyopaque, call: *rpc.protocol.CallBuilder) anyerror!void {
            const ctx: *CallContext = @ptrCast(@alignCast(ctx_ptr));
            const params_builder = try call.initParamsStruct(1, 1);
            var params = Params.Builder.wrap(params_builder);
            if (ctx.build) |build_fn| {
                try build_fn(ctx.user_ctx, &params);
            }
            try call.setEmptyCapTable();
        }

        fn callReturn(ctx_ptr: *anyopaque, peer: *rpc.peer.Peer, ret: rpc.protocol.Return, caps: *const rpc.cap_table.InboundCapTable) anyerror!void {
            const ctx: *CallContext = @ptrCast(@alignCast(ctx_ptr));
            defer peer.allocator.destroy(ctx);
            var response: Response = undefined;
            switch (ret.tag) {
                .results => {
                    const payload = ret.results orelse return error.MissingReturnPayload;
                    const struct_reader = try payload.content.getStruct();
                    const results = Results.Reader.wrap(struct_reader);
                    response = .{ .results = results };
                },
                .exception => {
                    const ex = ret.exception orelse return error.MissingException;
                    response = .{ .exception = ex };
                },
                .canceled => response = .canceled,
                .results_sent_elsewhere => response = .results_sent_elsewhere,
                .take_from_other_question => {
                    const qid = ret.take_from_other_question orelse return error.MissingQuestionId;
                    response = .{ .take_from_other_question = qid };
                },
                .accept_from_third_party => response = .accept_from_third_party,
            }
            try ctx.callback(ctx.user_ctx, peer, response, caps);
        }

        fn handleCall(server: *Server, peer: *rpc.peer.Peer, call: rpc.protocol.Call, caps: *const rpc.cap_table.InboundCapTable) anyerror!void {
            const params_struct = try call.params.content.getStruct();
            const params = Params.Reader.wrap(params_struct);
            var ctx = ReturnContext{
                .server = server,
                .peer = peer,
                .params = params,
                .caps = caps,
            };
            try peer.sendReturnResults(call.question_id, &ctx, buildReturn);
        }

        fn buildReturn(ctx_ptr: *anyopaque, ret: *rpc.protocol.ReturnBuilder) anyerror!void {
            const ctx: *ReturnContext = @ptrCast(@alignCast(ctx_ptr));
            const results_builder = try ret.initResultsStruct(0, 1);
            var results = Results.Builder.wrap(results_builder);
            try ctx.server.vtable.list(ctx.server.ctx, ctx.peer, ctx.params, &results, ctx.caps);
            try ret.setEmptyCapTable();
        }
    };

    pub const Client = struct {
        peer: *rpc.peer.Peer,
        cap_id: u32,

        pub fn init(peer: *rpc.peer.Peer, cap_id: u32) Client {
            return .{ .peer = peer, .cap_id = cap_id };
        }

        pub fn callGet(self: *Client, user_ctx: *anyopaque, build: ?Get.BuildFn, on_return: Get.Callback) !u32 {
            const ctx = try self.peer.allocator.create(Get.CallContext);
            ctx.* = .{ .user_ctx = user_ctx, .build = build, .callback = on_return };
            return self.peer.sendCall(self.cap_id, interface_id, Get.ordinal, ctx, Get.callBuild, Get.callReturn);
        }

        pub fn callSet(self: *Client, user_ctx: *anyopaque, build: ?Set.BuildFn, on_return: Set.Callback) !u32 {
            const ctx = try self.peer.allocator.create(Set.CallContext);
            ctx.* = .{ .user_ctx = user_ctx, .build = build, .callback = on_return };
            return self.peer.sendCall(self.cap_id, interface_id, Set.ordinal, ctx, Set.callBuild, Set.callReturn);
        }

        pub fn callDelete(self: *Client, user_ctx: *anyopaque, build: ?Delete.BuildFn, on_return: Delete.Callback) !u32 {
            const ctx = try self.peer.allocator.create(Delete.CallContext);
            ctx.* = .{ .user_ctx = user_ctx, .build = build, .callback = on_return };
            return self.peer.sendCall(self.cap_id, interface_id, Delete.ordinal, ctx, Delete.callBuild, Delete.callReturn);
        }

        pub fn callList(self: *Client, user_ctx: *anyopaque, build: ?List.BuildFn, on_return: List.Callback) !u32 {
            const ctx = try self.peer.allocator.create(List.CallContext);
            ctx.* = .{ .user_ctx = user_ctx, .build = build, .callback = on_return };
            return self.peer.sendCall(self.cap_id, interface_id, List.ordinal, ctx, List.callBuild, List.callReturn);
        }

        pub fn fromBootstrap(peer: *rpc.peer.Peer, user_ctx: *anyopaque, callback: BootstrapCallback) !u32 {
            return bootstrap(peer, user_ctx, callback);
        }
    };

    pub const BootstrapResponse = union(enum) {
        client: Client,
        exception: rpc.protocol.Exception,
        canceled,
        results_sent_elsewhere,
        take_from_other_question: u32,
        accept_from_third_party,
    };
    pub const BootstrapCallback = *const fn (ctx: *anyopaque, peer: *rpc.peer.Peer, response: BootstrapResponse) anyerror!void;

    const BootstrapContext = struct {
        user_ctx: *anyopaque,
        callback: BootstrapCallback,
    };

    fn bootstrapReturn(ctx_ptr: *anyopaque, peer: *rpc.peer.Peer, ret: rpc.protocol.Return, caps: *const rpc.cap_table.InboundCapTable) anyerror!void {
        const ctx: *BootstrapContext = @ptrCast(@alignCast(ctx_ptr));
        defer peer.allocator.destroy(ctx);
        var response: BootstrapResponse = undefined;
        switch (ret.tag) {
            .results => {
                const payload = ret.results orelse return error.MissingReturnPayload;
                const cap = try payload.content.getCapability();
                const resolved = try caps.resolveCapability(cap);
                switch (resolved) {
                    .imported => |imported| response = .{ .client = Client.init(peer, imported.id) },
                    else => return error.UnexpectedBootstrapCapability,
                }
            },
            .exception => {
                const ex = ret.exception orelse return error.MissingException;
                response = .{ .exception = ex };
            },
            .canceled => response = .canceled,
            .results_sent_elsewhere => response = .results_sent_elsewhere,
            .take_from_other_question => {
                const qid = ret.take_from_other_question orelse return error.MissingQuestionId;
                response = .{ .take_from_other_question = qid };
            },
            .accept_from_third_party => response = .accept_from_third_party,
        }
        try ctx.callback(ctx.user_ctx, peer, response);
    }

    pub fn bootstrap(peer: *rpc.peer.Peer, user_ctx: *anyopaque, callback: BootstrapCallback) !u32 {
        const ctx = try peer.allocator.create(BootstrapContext);
        ctx.* = .{ .user_ctx = user_ctx, .callback = callback };
        return peer.sendBootstrap(ctx, bootstrapReturn);
    }

    pub const Server = struct {
        ctx: *anyopaque,
        vtable: VTable,
    };

    pub const VTable = struct {
        get: Get.Handler,
        set: Set.Handler,
        delete: Delete.Handler,
        list: List.Handler,
    };

    pub fn exportServer(peer: *rpc.peer.Peer, server: *Server) !u32 {
        return peer.addExport(.{ .ctx = server, .on_call = onCall });
    }

    pub fn setBootstrap(peer: *rpc.peer.Peer, server: *Server) !u32 {
        return peer.setBootstrap(.{ .ctx = server, .on_call = onCall });
    }

    fn onCall(ctx: *anyopaque, peer: *rpc.peer.Peer, call: rpc.protocol.Call, caps: *const rpc.cap_table.InboundCapTable) anyerror!void {
        const server: *Server = @ptrCast(@alignCast(ctx));
        switch (call.method_id) {
            Get.ordinal => try Get.handleCall(server, peer, call, caps),
            Set.ordinal => try Set.handleCall(server, peer, call, caps),
            Delete.ordinal => try Delete.handleCall(server, peer, call, caps),
            List.ordinal => try List.handleCall(server, peer, call, caps),
            else => try peer.sendReturnException(call.question_id, "unknown method"),
        }
    }
};

pub const GetParams = struct {
    fn EnumListReader(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !EnumType {
                return std.meta.intToEnum(EnumType, try self._list.get(index)) catch return error.InvalidEnumValue;
            }

            pub fn raw(self: @This()) message.U16ListReader {
                return self._list;
            }
        };
    }

    fn EnumListBuilder(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn set(self: @This(), index: u32, value: EnumType) !void {
                try self._list.set(index, @intFromEnum(value));
            }

            pub fn raw(self: @This()) message.U16ListBuilder {
                return self._list;
            }
        };
    }

    fn StructListReader(comptime StructType: type) type {
        return struct {
            _list: message.StructListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Reader {
                const item = try self._list.get(index);
                return StructType.Reader.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListReader {
                return self._list;
            }
        };
    }

    fn StructListBuilder(comptime StructType: type) type {
        return struct {
            _list: message.StructListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Builder {
                const item = try self._list.get(index);
                return StructType.Builder.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListBuilder {
                return self._list;
            }
        };
    }

    const DataListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) ![]const u8 {
            return try self._list.getData(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const DataListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, value: []const u8) !void {
            try self._list.setData(index, value);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    const CapabilityListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) !message.Capability {
            return try self._list.getCapability(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const CapabilityListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, cap: message.Capability) !void {
            try self._list.setCapability(index, cap);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn getKey(self: Reader) ![]const u8 {
            if (self._reader.isPointerNull(0)) return "";
            return try self._reader.readText(0);
        }
    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(0, 1);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn setKey(self: *Builder, value: []const u8) !void {
            try self._builder.writeText(0, value);
        }
    };
};

pub const GetResults = struct {
    fn EnumListReader(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !EnumType {
                return std.meta.intToEnum(EnumType, try self._list.get(index)) catch return error.InvalidEnumValue;
            }

            pub fn raw(self: @This()) message.U16ListReader {
                return self._list;
            }
        };
    }

    fn EnumListBuilder(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn set(self: @This(), index: u32, value: EnumType) !void {
                try self._list.set(index, @intFromEnum(value));
            }

            pub fn raw(self: @This()) message.U16ListBuilder {
                return self._list;
            }
        };
    }

    fn StructListReader(comptime StructType: type) type {
        return struct {
            _list: message.StructListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Reader {
                const item = try self._list.get(index);
                return StructType.Reader.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListReader {
                return self._list;
            }
        };
    }

    fn StructListBuilder(comptime StructType: type) type {
        return struct {
            _list: message.StructListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Builder {
                const item = try self._list.get(index);
                return StructType.Builder.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListBuilder {
                return self._list;
            }
        };
    }

    const DataListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) ![]const u8 {
            return try self._list.getData(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const DataListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, value: []const u8) !void {
            try self._list.setData(index, value);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    const CapabilityListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) !message.Capability {
            return try self._list.getCapability(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const CapabilityListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, cap: message.Capability) !void {
            try self._list.setCapability(index, cap);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn getValue(self: Reader) ![]const u8 {
            if (self._reader.isPointerNull(0)) return &[_]u8{};
            return try self._reader.readData(0);
        }

        pub fn getFound(self: Reader) !bool {
            return self._reader.readBool(0, 0) != false;
        }
    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(1, 1);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn setValue(self: *Builder, value: []const u8) !void {
            try self._builder.writeData(0, value);
        }

        pub fn setFound(self: *Builder, value: bool) !void {
            self._builder.writeBool(0, 0, value != false);
        }
    };
};

pub const SetParams = struct {
    fn EnumListReader(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !EnumType {
                return std.meta.intToEnum(EnumType, try self._list.get(index)) catch return error.InvalidEnumValue;
            }

            pub fn raw(self: @This()) message.U16ListReader {
                return self._list;
            }
        };
    }

    fn EnumListBuilder(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn set(self: @This(), index: u32, value: EnumType) !void {
                try self._list.set(index, @intFromEnum(value));
            }

            pub fn raw(self: @This()) message.U16ListBuilder {
                return self._list;
            }
        };
    }

    fn StructListReader(comptime StructType: type) type {
        return struct {
            _list: message.StructListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Reader {
                const item = try self._list.get(index);
                return StructType.Reader.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListReader {
                return self._list;
            }
        };
    }

    fn StructListBuilder(comptime StructType: type) type {
        return struct {
            _list: message.StructListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Builder {
                const item = try self._list.get(index);
                return StructType.Builder.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListBuilder {
                return self._list;
            }
        };
    }

    const DataListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) ![]const u8 {
            return try self._list.getData(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const DataListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, value: []const u8) !void {
            try self._list.setData(index, value);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    const CapabilityListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) !message.Capability {
            return try self._list.getCapability(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const CapabilityListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, cap: message.Capability) !void {
            try self._list.setCapability(index, cap);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn getKey(self: Reader) ![]const u8 {
            if (self._reader.isPointerNull(0)) return "";
            return try self._reader.readText(0);
        }

        pub fn getValue(self: Reader) ![]const u8 {
            if (self._reader.isPointerNull(1)) return &[_]u8{};
            return try self._reader.readData(1);
        }
    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(0, 2);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn setKey(self: *Builder, value: []const u8) !void {
            try self._builder.writeText(0, value);
        }

        pub fn setValue(self: *Builder, value: []const u8) !void {
            try self._builder.writeData(1, value);
        }
    };
};

pub const SetResults = struct {
    fn EnumListReader(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !EnumType {
                return std.meta.intToEnum(EnumType, try self._list.get(index)) catch return error.InvalidEnumValue;
            }

            pub fn raw(self: @This()) message.U16ListReader {
                return self._list;
            }
        };
    }

    fn EnumListBuilder(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn set(self: @This(), index: u32, value: EnumType) !void {
                try self._list.set(index, @intFromEnum(value));
            }

            pub fn raw(self: @This()) message.U16ListBuilder {
                return self._list;
            }
        };
    }

    fn StructListReader(comptime StructType: type) type {
        return struct {
            _list: message.StructListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Reader {
                const item = try self._list.get(index);
                return StructType.Reader.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListReader {
                return self._list;
            }
        };
    }

    fn StructListBuilder(comptime StructType: type) type {
        return struct {
            _list: message.StructListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Builder {
                const item = try self._list.get(index);
                return StructType.Builder.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListBuilder {
                return self._list;
            }
        };
    }

    const DataListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) ![]const u8 {
            return try self._list.getData(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const DataListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, value: []const u8) !void {
            try self._list.setData(index, value);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    const CapabilityListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) !message.Capability {
            return try self._list.getCapability(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const CapabilityListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, cap: message.Capability) !void {
            try self._list.setCapability(index, cap);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn getEntry(self: Reader) !Entry.Reader {
            const value = try self._reader.readStruct(0);
            return Entry.Reader{ ._reader = value };
        }
    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(0, 1);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn initEntry(self: *Builder) !Entry.Builder {
            const builder = try self._builder.initStruct(0, 1, 2);
            return Entry.Builder{ ._builder = builder };
        }
    };
};

pub const DeleteParams = struct {
    fn EnumListReader(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !EnumType {
                return std.meta.intToEnum(EnumType, try self._list.get(index)) catch return error.InvalidEnumValue;
            }

            pub fn raw(self: @This()) message.U16ListReader {
                return self._list;
            }
        };
    }

    fn EnumListBuilder(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn set(self: @This(), index: u32, value: EnumType) !void {
                try self._list.set(index, @intFromEnum(value));
            }

            pub fn raw(self: @This()) message.U16ListBuilder {
                return self._list;
            }
        };
    }

    fn StructListReader(comptime StructType: type) type {
        return struct {
            _list: message.StructListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Reader {
                const item = try self._list.get(index);
                return StructType.Reader.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListReader {
                return self._list;
            }
        };
    }

    fn StructListBuilder(comptime StructType: type) type {
        return struct {
            _list: message.StructListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Builder {
                const item = try self._list.get(index);
                return StructType.Builder.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListBuilder {
                return self._list;
            }
        };
    }

    const DataListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) ![]const u8 {
            return try self._list.getData(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const DataListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, value: []const u8) !void {
            try self._list.setData(index, value);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    const CapabilityListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) !message.Capability {
            return try self._list.getCapability(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const CapabilityListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, cap: message.Capability) !void {
            try self._list.setCapability(index, cap);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn getKey(self: Reader) ![]const u8 {
            if (self._reader.isPointerNull(0)) return "";
            return try self._reader.readText(0);
        }
    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(0, 1);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn setKey(self: *Builder, value: []const u8) !void {
            try self._builder.writeText(0, value);
        }
    };
};

pub const DeleteResults = struct {
    fn EnumListReader(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !EnumType {
                return std.meta.intToEnum(EnumType, try self._list.get(index)) catch return error.InvalidEnumValue;
            }

            pub fn raw(self: @This()) message.U16ListReader {
                return self._list;
            }
        };
    }

    fn EnumListBuilder(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn set(self: @This(), index: u32, value: EnumType) !void {
                try self._list.set(index, @intFromEnum(value));
            }

            pub fn raw(self: @This()) message.U16ListBuilder {
                return self._list;
            }
        };
    }

    fn StructListReader(comptime StructType: type) type {
        return struct {
            _list: message.StructListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Reader {
                const item = try self._list.get(index);
                return StructType.Reader.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListReader {
                return self._list;
            }
        };
    }

    fn StructListBuilder(comptime StructType: type) type {
        return struct {
            _list: message.StructListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Builder {
                const item = try self._list.get(index);
                return StructType.Builder.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListBuilder {
                return self._list;
            }
        };
    }

    const DataListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) ![]const u8 {
            return try self._list.getData(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const DataListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, value: []const u8) !void {
            try self._list.setData(index, value);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    const CapabilityListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) !message.Capability {
            return try self._list.getCapability(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const CapabilityListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, cap: message.Capability) !void {
            try self._list.setCapability(index, cap);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn getFound(self: Reader) !bool {
            return self._reader.readBool(0, 0) != false;
        }
    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(1, 0);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn setFound(self: *Builder, value: bool) !void {
            self._builder.writeBool(0, 0, value != false);
        }
    };
};

pub const ListParams = struct {
    fn EnumListReader(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !EnumType {
                return std.meta.intToEnum(EnumType, try self._list.get(index)) catch return error.InvalidEnumValue;
            }

            pub fn raw(self: @This()) message.U16ListReader {
                return self._list;
            }
        };
    }

    fn EnumListBuilder(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn set(self: @This(), index: u32, value: EnumType) !void {
                try self._list.set(index, @intFromEnum(value));
            }

            pub fn raw(self: @This()) message.U16ListBuilder {
                return self._list;
            }
        };
    }

    fn StructListReader(comptime StructType: type) type {
        return struct {
            _list: message.StructListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Reader {
                const item = try self._list.get(index);
                return StructType.Reader.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListReader {
                return self._list;
            }
        };
    }

    fn StructListBuilder(comptime StructType: type) type {
        return struct {
            _list: message.StructListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Builder {
                const item = try self._list.get(index);
                return StructType.Builder.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListBuilder {
                return self._list;
            }
        };
    }

    const DataListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) ![]const u8 {
            return try self._list.getData(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const DataListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, value: []const u8) !void {
            try self._list.setData(index, value);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    const CapabilityListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) !message.Capability {
            return try self._list.getCapability(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const CapabilityListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, cap: message.Capability) !void {
            try self._list.setCapability(index, cap);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn getPrefix(self: Reader) ![]const u8 {
            if (self._reader.isPointerNull(0)) return "";
            return try self._reader.readText(0);
        }

        pub fn getLimit(self: Reader) !u32 {
            const raw = self._reader.readU32(0);
            const value = raw ^ @as(u32, 0);
            return value;
        }
    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(1, 1);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn setPrefix(self: *Builder, value: []const u8) !void {
            try self._builder.writeText(0, value);
        }

        pub fn setLimit(self: *Builder, value: u32) !void {
            const stored = @as(u32, @bitCast(value)) ^ @as(u32, 0);
            self._builder.writeU32(0, stored);
        }
    };
};

pub const ListResults = struct {
    fn EnumListReader(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !EnumType {
                return std.meta.intToEnum(EnumType, try self._list.get(index)) catch return error.InvalidEnumValue;
            }

            pub fn raw(self: @This()) message.U16ListReader {
                return self._list;
            }
        };
    }

    fn EnumListBuilder(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn set(self: @This(), index: u32, value: EnumType) !void {
                try self._list.set(index, @intFromEnum(value));
            }

            pub fn raw(self: @This()) message.U16ListBuilder {
                return self._list;
            }
        };
    }

    fn StructListReader(comptime StructType: type) type {
        return struct {
            _list: message.StructListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Reader {
                const item = try self._list.get(index);
                return StructType.Reader.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListReader {
                return self._list;
            }
        };
    }

    fn StructListBuilder(comptime StructType: type) type {
        return struct {
            _list: message.StructListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Builder {
                const item = try self._list.get(index);
                return StructType.Builder.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListBuilder {
                return self._list;
            }
        };
    }

    const DataListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) ![]const u8 {
            return try self._list.getData(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const DataListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, value: []const u8) !void {
            try self._list.setData(index, value);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    const CapabilityListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) !message.Capability {
            return try self._list.getCapability(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const CapabilityListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, cap: message.Capability) !void {
            try self._list.setCapability(index, cap);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn getEntries(self: Reader) !StructListReader(Entry) {
            const raw = try self._reader.readStructList(0);
            return StructListReader(Entry){ ._list = raw };
        }
    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(0, 1);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn initEntries(self: *Builder, element_count: u32) !StructListBuilder(Entry) {
            const raw = try self._builder.writeStructList(0, element_count, 1, 2);
            return StructListBuilder(Entry){ ._list = raw };
        }
    };
};
