server: zig build server -Doptimize=ReleaseFast -- --port 9000 --quiet
# client: sleep 2 && zig build client -Doptimize=ReleaseSafe -- --port 9000
zig build stressor -Doptimize=ReleaseFast -- --host {{ host }}
