// Generated by capnpc-zig
// Source: examples/addressbook.capnp

const std = @import("std");
const capnpc = @import("capnpc-zig");
const message = capnpc.message;
const schema = capnpc.schema;

pub const CAPNP_SCHEMA_MANIFEST_JSON: []const u8 = "{\"schema\":\"examples/addressbook.capnp\",\"module\":\"addressbook\",\"serde\":[{\"id\":10897574556987344291,\"type_name\":\"AddressBook\",\"to_json_export\":\"capnp_addressbook_address_book_to_json\",\"from_json_export\":\"capnp_addressbook_address_book_from_json\"},{\"id\":11903459242805649238,\"type_name\":\"Person\",\"to_json_export\":\"capnp_addressbook_person_to_json\",\"from_json_export\":\"capnp_addressbook_person_from_json\"},{\"id\":15991255646970106953,\"type_name\":\"Person.PhoneNumber\",\"to_json_export\":\"capnp_addressbook_person_phone_number_to_json\",\"from_json_export\":\"capnp_addressbook_person_phone_number_from_json\"}]}";
pub fn capnpSchemaManifestJson() []const u8 {
    return CAPNP_SCHEMA_MANIFEST_JSON;
}

pub const AddressBook = struct {
    const StructListReader = message.typed_list_helpers.StructListReader;
    const StructListBuilder = message.typed_list_helpers.StructListBuilder;

    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn hasPeople(self: Reader) bool {
            return !self._reader.isPointerNull(0);
        }

        pub fn getPeople(self: Reader) !StructListReader(Person) {
            if (self._reader.isPointerNull(0)) return StructListReader(Person){ ._list = self._reader.emptyStructList() };
            const raw = try self._reader.readStructList(0);
            return StructListReader(Person){ ._list = raw };
        }
    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(0, 1);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn hasPeople(self: Builder) bool {
            return !self._builder.isPointerNull(0);
        }

        pub fn initPeople(self: *Builder, element_count: u32) !StructListBuilder(Person) {
            const raw = try self._builder.writeStructList(0, element_count, 1, 5);
            return StructListBuilder(Person){ ._list = raw };
        }
    };
};

pub const Person = struct {
    const StructListReader = message.typed_list_helpers.StructListReader;
    const StructListBuilder = message.typed_list_helpers.StructListBuilder;

    pub const WhichTag = enum(u16) {
        unemployed = 0,
        employer = 1,
        school = 2,
        selfEmployed = 3,
    };

    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn whichOrdinal(self: Reader) u16 {
            return self._reader.readUnionDiscriminant(4);
        }

        pub fn which(self: Reader) error{InvalidEnumValue}!WhichTag {
            return std.enums.fromInt(WhichTag, self.whichOrdinal()) orelse return error.InvalidEnumValue;
        }

        pub fn getId(self: Reader) !u32 {
            return self._reader.readU32(0);
        }

        pub fn hasName(self: Reader) bool {
            return !self._reader.isPointerNull(0);
        }

        pub fn getName(self: Reader) ![]const u8 {
            if (self._reader.isPointerNull(0)) return "";
            return try self._reader.readText(0);
        }

        pub fn hasEmail(self: Reader) bool {
            return !self._reader.isPointerNull(1);
        }

        pub fn getEmail(self: Reader) ![]const u8 {
            if (self._reader.isPointerNull(1)) return "";
            return try self._reader.readText(1);
        }

        pub fn hasPhones(self: Reader) bool {
            return !self._reader.isPointerNull(2);
        }

        pub fn getPhones(self: Reader) !StructListReader(Person.PhoneNumber) {
            if (self._reader.isPointerNull(2)) return StructListReader(Person.PhoneNumber){ ._list = self._reader.emptyStructList() };
            const raw = try self._reader.readStructList(2);
            return StructListReader(Person.PhoneNumber){ ._list = raw };
        }

        pub fn hasAvatar(self: Reader) bool {
            return !self._reader.isPointerNull(3);
        }

        pub fn getAvatar(self: Reader) ![]const u8 {
            if (self._reader.isPointerNull(3)) return &[_]u8{};
            return try self._reader.readData(3);
        }

        pub fn getUnemployed(self: Reader) !void {
            if ((try self.which()) != .unemployed) return error.WrongUnionMember;
            return {};
        }

        pub fn hasEmployer(self: Reader) bool {
            if (self._reader.readUnionDiscriminant(4) != 1) return false;
            return !self._reader.isPointerNull(4);
        }

        pub fn getEmployer(self: Reader) ![]const u8 {
            if ((try self.which()) != .employer) return error.WrongUnionMember;
            if (self._reader.isPointerNull(4)) return "";
            return try self._reader.readText(4);
        }

        pub fn hasSchool(self: Reader) bool {
            if (self._reader.readUnionDiscriminant(4) != 2) return false;
            return !self._reader.isPointerNull(4);
        }

        pub fn getSchool(self: Reader) ![]const u8 {
            if ((try self.which()) != .school) return error.WrongUnionMember;
            if (self._reader.isPointerNull(4)) return "";
            return try self._reader.readText(4);
        }

        pub fn getSelfEmployed(self: Reader) !void {
            if ((try self.which()) != .selfEmployed) return error.WrongUnionMember;
            return {};
        }
    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(1, 5);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn setId(self: *Builder, value: u32) !void {
            self._builder.writeU32(0, @bitCast(value));
        }

        pub fn hasName(self: Builder) bool {
            return !self._builder.isPointerNull(0);
        }

        pub fn setName(self: *Builder, value: []const u8) !void {
            try self._builder.writeText(0, value);
        }

        pub fn hasEmail(self: Builder) bool {
            return !self._builder.isPointerNull(1);
        }

        pub fn setEmail(self: *Builder, value: []const u8) !void {
            try self._builder.writeText(1, value);
        }

        pub fn hasPhones(self: Builder) bool {
            return !self._builder.isPointerNull(2);
        }

        pub fn initPhones(self: *Builder, element_count: u32) !StructListBuilder(Person.PhoneNumber) {
            const raw = try self._builder.writeStructList(2, element_count, 1, 1);
            return StructListBuilder(Person.PhoneNumber){ ._list = raw };
        }

        pub fn hasAvatar(self: Builder) bool {
            return !self._builder.isPointerNull(3);
        }

        pub fn setAvatar(self: *Builder, value: []const u8) !void {
            try self._builder.writeData(3, value);
        }

        pub fn setUnemployed(self: *Builder, value: void) !void {
            self._builder.writeU16(4, 0);
            _ = value;
        }

        pub fn hasEmployer(self: Builder) bool {
            if (self._builder.readUnionDiscriminant(4) != 1) return false;
            return !self._builder.isPointerNull(4);
        }

        pub fn setEmployer(self: *Builder, value: []const u8) !void {
            self._builder.writeU16(4, 1);
            try self._builder.writeText(4, value);
        }

        pub fn hasSchool(self: Builder) bool {
            if (self._builder.readUnionDiscriminant(4) != 2) return false;
            return !self._builder.isPointerNull(4);
        }

        pub fn setSchool(self: *Builder, value: []const u8) !void {
            self._builder.writeU16(4, 2);
            try self._builder.writeText(4, value);
        }

        pub fn setSelfEmployed(self: *Builder, value: void) !void {
            self._builder.writeU16(4, 3);
            _ = value;
        }
    };
    pub const PhoneNumber = struct {
        pub const Reader = struct {
            _reader: message.StructReader,

            pub fn init(msg: *const message.Message) !@This() {
                const root = try msg.getRootStruct();
                return .{ ._reader = root };
            }

            pub fn wrap(reader: message.StructReader) @This() {
                return .{ ._reader = reader };
            }

            pub const EnumOrdinals = struct {
                _reader: message.StructReader,

                pub fn getType(self: @This()) !u16 {
                    return self._reader.readU16(0);
                }
            };

            pub fn enumOrdinals(self: @This()) EnumOrdinals {
                return .{ ._reader = self._reader };
            }

            pub fn hasNumber(self: @This()) bool {
                return !self._reader.isPointerNull(0);
            }

            pub fn getNumber(self: @This()) ![]const u8 {
                if (self._reader.isPointerNull(0)) return "";
                return try self._reader.readText(0);
            }

            pub fn getType(self: @This()) !Person.PhoneType {
                const ordinal = try self.enumOrdinals().getType();
                return std.enums.fromInt(Person.PhoneType, ordinal) orelse return error.InvalidEnumValue;
            }
        };

        pub const Builder = struct {
            _builder: message.StructBuilder,

            pub fn init(msg: *message.MessageBuilder) !@This() {
                const builder = try msg.allocateStruct(1, 1);
                return .{ ._builder = builder };
            }

            pub fn wrap(builder: message.StructBuilder) @This() {
                return .{ ._builder = builder };
            }

            pub const EnumOrdinals = struct {
                _builder: message.StructBuilder,

                pub fn setType(self: @This(), value: u16) !void {
                    self._builder.writeU16(0, value);
                }
            };

            pub fn enumOrdinals(self: @This()) EnumOrdinals {
                return .{ ._builder = self._builder };
            }

            pub fn hasNumber(self: @This()) bool {
                return !self._builder.isPointerNull(0);
            }

            pub fn setNumber(self: *@This(), value: []const u8) !void {
                try self._builder.writeText(0, value);
            }

            pub fn setType(self: *@This(), value: Person.PhoneType) !void {
                return self.enumOrdinals().setType(@as(u16, @backingInt(value)));
            }
        };
    };

    pub const PhoneType = enum(u16) {
        Mobile = 0,
        Home = 1,
        Work = 2,
    };
};
