// Generated by capnpc-zig
// Source: examples/pingpong.capnp

const std = @import("std");
const capnpc = @import("capnpc-zig");
const message = capnpc.message;
const schema = capnpc.schema;
const rpc = capnpc.rpc;

pub const PingPong = struct {
    pub const interface_id: u64 = 0xcf57ad2c7f5dc67b;
    pub const Method = enum(u16) {
        Ping = 0,
    };

    pub const Ping = struct {
        pub const ordinal: u16 = 0;
        pub const Params = PingParams;
        pub const Results = PingResults;
        pub const BuildFn = *const fn (ctx: *anyopaque, params: *Params.Builder) anyerror!void;
        pub const Handler = *const fn (ctx: *anyopaque, peer: *rpc.peer.Peer, params: Params.Reader, results: *Results.Builder, caps: *const rpc.cap_table.InboundCapTable) anyerror!void;
        pub const Response = union(enum) {
            results: Results.Reader,
            exception: rpc.protocol.Exception,
            canceled,
            results_sent_elsewhere,
            take_from_other_question: u32,
            accept_from_third_party,
        };
        pub const Callback = *const fn (ctx: *anyopaque, peer: *rpc.peer.Peer, response: Response, caps: *const rpc.cap_table.InboundCapTable) anyerror!void;

        const CallContext = struct {
            user_ctx: *anyopaque,
            build: ?BuildFn,
            callback: Callback,
        };

        const ReturnContext = struct {
            server: *Server,
            peer: *rpc.peer.Peer,
            params: Params.Reader,
            caps: *const rpc.cap_table.InboundCapTable,
        };

        fn callBuild(ctx_ptr: *anyopaque, call: *rpc.protocol.CallBuilder) anyerror!void {
            const ctx: *CallContext = @ptrCast(@alignCast(ctx_ptr));
            const params_builder = try call.initParamsStruct(1, 0);
            var params = Params.Builder.wrap(params_builder);
            if (ctx.build) |build_fn| {
                try build_fn(ctx.user_ctx, &params);
            }
            try call.setEmptyCapTable();
        }

        fn callReturn(ctx_ptr: *anyopaque, peer: *rpc.peer.Peer, ret: rpc.protocol.Return, caps: *const rpc.cap_table.InboundCapTable) anyerror!void {
            const ctx: *CallContext = @ptrCast(@alignCast(ctx_ptr));
            defer peer.allocator.destroy(ctx);
            var response: Response = undefined;
            switch (ret.tag) {
                .results => {
                    const payload = ret.results orelse return error.MissingReturnPayload;
                    const struct_reader = try payload.content.getStruct();
                    const results = Results.Reader.wrap(struct_reader);
                    response = .{ .results = results };
                },
                .exception => {
                    const ex = ret.exception orelse return error.MissingException;
                    response = .{ .exception = ex };
                },
                .canceled => response = .canceled,
                .results_sent_elsewhere => response = .results_sent_elsewhere,
                .take_from_other_question => {
                    const qid = ret.take_from_other_question orelse return error.MissingQuestionId;
                    response = .{ .take_from_other_question = qid };
                },
                .accept_from_third_party => response = .accept_from_third_party,
            }
            try ctx.callback(ctx.user_ctx, peer, response, caps);
        }

        fn handleCall(server: *Server, peer: *rpc.peer.Peer, call: rpc.protocol.Call, caps: *const rpc.cap_table.InboundCapTable) anyerror!void {
            const params_struct = try call.params.content.getStruct();
            const params = Params.Reader.wrap(params_struct);
            var ctx = ReturnContext{
                .server = server,
                .peer = peer,
                .params = params,
                .caps = caps,
            };
            try peer.sendReturnResults(call.question_id, &ctx, buildReturn);
        }

        fn buildReturn(ctx_ptr: *anyopaque, ret: *rpc.protocol.ReturnBuilder) anyerror!void {
            const ctx: *ReturnContext = @ptrCast(@alignCast(ctx_ptr));
            const results_builder = try ret.initResultsStruct(1, 0);
            var results = Results.Builder.wrap(results_builder);
            try ctx.server.vtable.ping(ctx.server.ctx, ctx.peer, ctx.params, &results, ctx.caps);
            try ret.setEmptyCapTable();
        }
    };

    pub const Client = struct {
        peer: *rpc.peer.Peer,
        cap_id: u32,

        pub fn init(peer: *rpc.peer.Peer, cap_id: u32) Client {
            return .{ .peer = peer, .cap_id = cap_id };
        }

        pub fn callPing(self: *Client, user_ctx: *anyopaque, build: ?Ping.BuildFn, on_return: Ping.Callback) !u32 {
            const ctx = try self.peer.allocator.create(Ping.CallContext);
            ctx.* = .{ .user_ctx = user_ctx, .build = build, .callback = on_return };
            return self.peer.sendCall(self.cap_id, interface_id, Ping.ordinal, ctx, Ping.callBuild, Ping.callReturn);
        }

        pub fn fromBootstrap(peer: *rpc.peer.Peer, user_ctx: *anyopaque, callback: BootstrapCallback) !u32 {
            return bootstrap(peer, user_ctx, callback);
        }

    };

    pub const BootstrapResponse = union(enum) {
        client: Client,
        exception: rpc.protocol.Exception,
        canceled,
        results_sent_elsewhere,
        take_from_other_question: u32,
        accept_from_third_party,
    };
    pub const BootstrapCallback = *const fn (ctx: *anyopaque, peer: *rpc.peer.Peer, response: BootstrapResponse) anyerror!void;

    const BootstrapContext = struct {
        user_ctx: *anyopaque,
        callback: BootstrapCallback,
    };

    fn bootstrapReturn(ctx_ptr: *anyopaque, peer: *rpc.peer.Peer, ret: rpc.protocol.Return, caps: *const rpc.cap_table.InboundCapTable) anyerror!void {
        const ctx: *BootstrapContext = @ptrCast(@alignCast(ctx_ptr));
        defer peer.allocator.destroy(ctx);
        var response: BootstrapResponse = undefined;
        switch (ret.tag) {
            .results => {
                const payload = ret.results orelse return error.MissingReturnPayload;
                const cap = try payload.content.getCapability();
                const resolved = try caps.resolveCapability(cap);
                switch (resolved) {
                    .imported => |imported| response = .{ .client = Client.init(peer, imported.id) },
                    else => return error.UnexpectedBootstrapCapability,
                }
            },
            .exception => {
                const ex = ret.exception orelse return error.MissingException;
                response = .{ .exception = ex };
            },
            .canceled => response = .canceled,
            .results_sent_elsewhere => response = .results_sent_elsewhere,
            .take_from_other_question => {
                const qid = ret.take_from_other_question orelse return error.MissingQuestionId;
                response = .{ .take_from_other_question = qid };
            },
            .accept_from_third_party => response = .accept_from_third_party,
        }
        try ctx.callback(ctx.user_ctx, peer, response);
    }

    pub fn bootstrap(peer: *rpc.peer.Peer, user_ctx: *anyopaque, callback: BootstrapCallback) !u32 {
        const ctx = try peer.allocator.create(BootstrapContext);
        ctx.* = .{ .user_ctx = user_ctx, .callback = callback };
        return peer.sendBootstrap(ctx, bootstrapReturn);
    }

    pub const Server = struct {
        ctx: *anyopaque,
        vtable: VTable,
    };

    pub const VTable = struct {
        ping: Ping.Handler,
    };

    pub fn exportServer(peer: *rpc.peer.Peer, server: *Server) !u32 {
        return peer.addExport(.{ .ctx = server, .on_call = onCall });
    }

    pub fn setBootstrap(peer: *rpc.peer.Peer, server: *Server) !u32 {
        return peer.setBootstrap(.{ .ctx = server, .on_call = onCall });
    }

    fn onCall(ctx: *anyopaque, peer: *rpc.peer.Peer, call: rpc.protocol.Call, caps: *const rpc.cap_table.InboundCapTable) anyerror!void {
        const server: *Server = @ptrCast(@alignCast(ctx));
        switch (call.method_id) {
            Ping.ordinal => try Ping.handleCall(server, peer, call, caps),
            else => try peer.sendReturnException(call.question_id, "unknown method"),
        }
    }
};

pub const PingParams = struct {
    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn getCount(self: Reader) !u32 {
            const raw = self._reader.readU32(0);
            const value = raw ^ @as(u32, 0);
            return value;
        }

    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(1, 0);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn setCount(self: *Builder, value: u32) !void {
            self._builder.writeU32(0, @bitCast(value));
        }

    };
};

pub const PingResults = struct {
    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn getCount(self: Reader) !u32 {
            const raw = self._reader.readU32(0);
            const value = raw ^ @as(u32, 0);
            return value;
        }

    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(1, 0);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn setCount(self: *Builder, value: u32) !void {
            self._builder.writeU32(0, @bitCast(value));
        }

    };
};

