// Generated by capnpc-zig
// Source: examples/pingpong.capnp

const std = @import("std");
const capnpc = @import("capnpc-zig");
const message = capnpc.message;
const schema = capnpc.schema;
const rpc = capnpc.rpc;

pub const CAPNP_SCHEMA_MANIFEST_JSON: []const u8 = "{\"schema\":\"examples/pingpong.capnp\",\"module\":\"pingpong\",\"serde\":[{\"id\":10408369240078422827,\"type_name\":\"PingPong.PingParams\",\"to_json_export\":\"capnp_pingpong_ping_pong_ping_params_to_json\",\"from_json_export\":\"capnp_pingpong_ping_pong_ping_params_from_json\"},{\"id\":12204507717862133617,\"type_name\":\"PingPong.PingResults\",\"to_json_export\":\"capnp_pingpong_ping_pong_ping_results_to_json\",\"from_json_export\":\"capnp_pingpong_ping_pong_ping_results_from_json\"}]}";
pub fn capnpSchemaManifestJson() []const u8 {
    return CAPNP_SCHEMA_MANIFEST_JSON;
}

pub const PingPong = struct {
    pub const interface_id: u64 = 0xcf57ad2c7f5dc67b;
    pub const Method = enum(u16) {
        Ping = 0,
    };

    pub const Ping = struct {
        pub const ordinal: u16 = 0;
        pub const is_streaming: bool = false;
        pub const Params = PingPong.PingParams;
        pub const Results = PingPong.PingResults;
        pub const BuildFn = *const fn (ctx: *anyopaque, params: *Params.Builder) anyerror!void;
        pub const Handler = *const fn (ctx: *anyopaque, peer: *rpc.peer.Peer, params: Params.Reader, results: *Results.Builder, caps: *const rpc.caps.table.InboundCapTable) anyerror!void;
        pub const DeferredHandler = *const fn (ctx: *anyopaque, peer: *rpc.peer.Peer, params: Params.Reader, caps: *const rpc.caps.table.InboundCapTable, sender: ReturnSender) anyerror!void;
        pub const Response = union(enum) {
            results: Results.Reader,
            exception: rpc.wire.protocol.Exception,
            canceled,
            results_sent_elsewhere,
            take_from_other_question: u32,
            accept_from_third_party,

            /// Collapse this Response into its success payload or a typed
            /// rpc.peer.CallError. Classification comes from the exception's
            /// spec `Exception.Type`, so a disconnect reported by ANY
            /// implementation is recognized; every other exception is
            /// RemoteException (reason available on the union arm).
            pub fn unwrap(self: Response) rpc.peer.CallError!Results.Reader {
                return switch (self) {
                    .results => |r| r,
                    .exception => |ex| switch (ex.kind()) {
                        .disconnected => error.Disconnected,
                        // The spec has no distinct timeout type and classes
                        // timeouts as overloaded, so our own deadline sentinel
                        // still separates a local timeout from a remote's
                        // genuine backpressure.
                        .overloaded => if (std.mem.eql(u8, ex.reason, rpc.peer.deadline_reason))
                            error.CallTimedOut
                        else
                            error.RemoteException,
                        // .failed, .unimplemented (spec: treat like failed), and
                        // any future code. `else` is required: the enum is
                        // non-exhaustive because the wire field is remote-controlled.
                        else => error.RemoteException,
                    },
                    .canceled => error.Canceled,
                    .results_sent_elsewhere, .take_from_other_question, .accept_from_third_party => error.UnexpectedReturn,
                };
            }
        };
        pub const Callback = *const fn (ctx: *anyopaque, peer: *rpc.peer.Peer, response: Response, caps: *const rpc.caps.table.InboundCapTable) anyerror!void;

        const CallContext = struct {
            user_ctx: *anyopaque,
            build: ?BuildFn,
            callback: Callback,

            // Frees the heap ctx if the question is still outstanding at
            // Peer.deinit (the normal return path frees it in callReturn).
            fn deinitCtx(ctx_allocator: std.mem.Allocator, ctx_ptr: *anyopaque) void {
                const dead: *CallContext = @ptrCast(@alignCast(ctx_ptr));
                ctx_allocator.destroy(dead);
            }
        };

        const DirectReturnContext = struct {
            handler: Handler,
            ctx: *anyopaque,
            peer: *rpc.peer.Peer,
            params: Params.Reader,
            caps: *const rpc.caps.table.InboundCapTable,
        };

        pub const ReturnSender = struct {
            peer: *rpc.peer.Peer,
            question_id: u32,

            pub fn sendResults(self: ReturnSender, ctx: *anyopaque, build: *const fn (ctx: *anyopaque, ret: *rpc.wire.protocol.ReturnBuilder) anyerror!void) !void {
                try self.peer.sendReturnResults(self.question_id, ctx, build);
            }

            pub fn sendException(self: ReturnSender, reason: []const u8) !void {
                try self.peer.sendReturnException(self.question_id, reason);
            }
        };

        fn callBuild(ctx_ptr: *anyopaque, call: *rpc.wire.protocol.CallBuilder) anyerror!void {
            const ctx: *CallContext = @ptrCast(@alignCast(ctx_ptr));
            var payload = try call.payloadTyped();
            var params_any = try payload.initContent();
            const params_builder = try params_any.initStruct(1, 0);
            var params = Params.Builder.wrap(params_builder);
            if (ctx.build) |build_fn| {
                try build_fn(ctx.user_ctx, &params);
            }
            _ = try call.initCapTableTyped(0);
        }

        fn callReturn(ctx_ptr: *anyopaque, peer: *rpc.peer.Peer, ret: rpc.wire.protocol.Return, caps: *const rpc.caps.table.InboundCapTable) anyerror!void {
            const ctx: *CallContext = @ptrCast(@alignCast(ctx_ptr));
            defer peer.allocator.destroy(ctx);
            var response: Response = undefined;
            switch (ret.tag) {
                .results => {
                    const payload = ret.results orelse return error.MissingReturnPayload;
                    const struct_reader = try payload.content.getStruct();
                    const results = Results.Reader.wrap(struct_reader);
                    response = .{ .results = results };
                },
                .exception => {
                    const ex = ret.exception orelse return error.MissingException;
                    response = .{ .exception = ex };
                },
                .canceled => response = .canceled,
                .resultsSentElsewhere => response = .results_sent_elsewhere,
                .takeFromOtherQuestion => {
                    const qid = ret.take_from_other_question orelse return error.MissingQuestionId;
                    response = .{ .take_from_other_question = qid };
                },
                .awaitFromThirdParty => response = .accept_from_third_party,
            }
            try ctx.callback(ctx.user_ctx, peer, response, caps);
        }

        pub fn handleCallDirect(handler: Handler, deferred_handler: ?DeferredHandler, ctx: *anyopaque, peer: *rpc.peer.Peer, call: rpc.wire.protocol.Call, caps: *const rpc.caps.table.InboundCapTable) anyerror!void {
            const params_struct = try call.params.content.getStruct();
            const params = Params.Reader.wrap(params_struct);
            if (deferred_handler) |deferred_fn| {
                const sender = ReturnSender{ .peer = peer, .question_id = call.question_id };
                try deferred_fn(ctx, peer, params, caps, sender);
            } else {
                var dctx = DirectReturnContext{
                    .handler = handler,
                    .ctx = ctx,
                    .peer = peer,
                    .params = params,
                    .caps = caps,
                };
                try peer.sendReturnResults(call.question_id, &dctx, buildReturnDirect);
            }
        }

        fn handleCall(server: *Server, peer: *rpc.peer.Peer, call: rpc.wire.protocol.Call, caps: *const rpc.caps.table.InboundCapTable) anyerror!void {
            try handleCallDirect(server.vtable.ping, server.vtable.ping_deferred, server.ctx, peer, call, caps);
        }

        fn buildReturnDirect(ctx_ptr: *anyopaque, ret: *rpc.wire.protocol.ReturnBuilder) anyerror!void {
            const dctx: *DirectReturnContext = @ptrCast(@alignCast(ctx_ptr));
            var payload = try ret.payloadTyped();
            var results_any = try payload.initContent();
            const results_builder = try results_any.initStruct(1, 0);
            var results = Results.Builder.wrap(results_builder);
            try dctx.handler(dctx.ctx, dctx.peer, dctx.params, &results, dctx.caps);
        }
    };

    pub const Client = struct {
        peer: *rpc.peer.Peer,
        cap_id: u32,

        pub fn init(peer: *rpc.peer.Peer, cap_id: u32) Client {
            return .{ .peer = peer, .cap_id = cap_id };
        }

        /// Release the import ref this Client owns (balances the bootstrap-return
        /// retainCapability). Call at most once per owned Client; best-effort —
        /// peer teardown's import release is the backstop.
        pub fn release(self: Client) void {
            self.peer.releaseImport(self.cap_id, 1) catch {};
        }

        pub fn callPing(self: Client, user_ctx: *anyopaque, build: ?Ping.BuildFn, on_return: Ping.Callback) !u32 {
            const ctx = try self.peer.allocator.create(Ping.CallContext);
            errdefer self.peer.allocator.destroy(ctx);
            ctx.* = .{ .user_ctx = user_ctx, .build = build, .callback = on_return };
            const question_id = try self.peer.sendCall(self.cap_id, interface_id, Ping.ordinal, ctx, Ping.callBuild, Ping.callReturn);
            self.peer.setQuestionDeinitCtx(question_id, Ping.CallContext.deinitCtx);
            return question_id;
        }

        pub fn fromBootstrap(peer: *rpc.peer.Peer, user_ctx: *anyopaque, callback: BootstrapCallback) !u32 {
            return bootstrap(peer, user_ctx, callback);
        }
    };

    pub const PipelinedClient = struct {
        peer: *rpc.peer.Peer,
        question_id: u32,
        pointer_index: u16,

        pub fn callPing(self: PipelinedClient, user_ctx: *anyopaque, build: ?Ping.BuildFn, on_return: Ping.Callback) !u32 {
            const ctx = try self.peer.allocator.create(Ping.CallContext);
            errdefer self.peer.allocator.destroy(ctx);
            ctx.* = .{ .user_ctx = user_ctx, .build = build, .callback = on_return };
            const question_id = try self.peer.sendCallPromisedWithOps(self.question_id, &[_]rpc.wire.protocol.PromisedAnswerOp{.{ .tag = .getPointerField, .pointer_index = self.pointer_index }}, interface_id, Ping.ordinal, ctx, Ping.callBuild, Ping.callReturn);
            self.peer.setQuestionDeinitCtx(question_id, Ping.CallContext.deinitCtx);
            return question_id;
        }
    };

    pub const BootstrapResponse = union(enum) {
        client: Client,
        exception: rpc.wire.protocol.Exception,
        canceled,
        results_sent_elsewhere,
        take_from_other_question: u32,
        accept_from_third_party,

        /// Collapse this BootstrapResponse into its Client or a typed
        /// rpc.peer.CallError. Classification comes from the exception's
        /// spec `Exception.Type`, so a disconnect reported by ANY
        /// implementation is recognized; every other exception is
        /// RemoteException (reason available on the union arm).
        pub fn unwrap(self: BootstrapResponse) rpc.peer.CallError!Client {
            return switch (self) {
                .client => |c| c,
                .exception => |ex| switch (ex.kind()) {
                    .disconnected => error.Disconnected,
                    // The spec has no distinct timeout type and classes
                    // timeouts as overloaded, so our own deadline sentinel
                    // still separates a local timeout from a remote's
                    // genuine backpressure.
                    .overloaded => if (std.mem.eql(u8, ex.reason, rpc.peer.deadline_reason))
                        error.CallTimedOut
                    else
                        error.RemoteException,
                    // .failed, .unimplemented (spec: treat like failed), and
                    // any future code. `else` is required: the enum is
                    // non-exhaustive because the wire field is remote-controlled.
                    else => error.RemoteException,
                },
                .canceled => error.Canceled,
                .results_sent_elsewhere, .take_from_other_question, .accept_from_third_party => error.UnexpectedReturn,
            };
        }
    };
    pub const BootstrapCallback = *const fn (ctx: *anyopaque, peer: *rpc.peer.Peer, response: BootstrapResponse) anyerror!void;

    const BootstrapContext = struct {
        user_ctx: *anyopaque,
        callback: BootstrapCallback,

        fn deinitCtx(ctx_allocator: std.mem.Allocator, ctx_ptr: *anyopaque) void {
            const dead: *BootstrapContext = @ptrCast(@alignCast(ctx_ptr));
            ctx_allocator.destroy(dead);
        }
    };

    fn bootstrapReturn(ctx_ptr: *anyopaque, peer: *rpc.peer.Peer, ret: rpc.wire.protocol.Return, caps: *const rpc.caps.table.InboundCapTable) anyerror!void {
        const ctx: *BootstrapContext = @ptrCast(@alignCast(ctx_ptr));
        defer peer.allocator.destroy(ctx);
        var response: BootstrapResponse = undefined;
        switch (ret.tag) {
            .results => {
                const payload = ret.results orelse return error.MissingReturnPayload;
                const cap = try payload.content.getCapability();
                var mutable_caps = caps.*;
                try mutable_caps.retainCapability(cap);
                const resolved = try caps.resolveCapability(cap);
                switch (resolved) {
                    .imported => |imported| response = .{ .client = Client.init(peer, imported.id) },
                    else => return error.UnexpectedBootstrapCapability,
                }
            },
            .exception => {
                const ex = ret.exception orelse return error.MissingException;
                response = .{ .exception = ex };
            },
            .canceled => response = .canceled,
            .resultsSentElsewhere => response = .results_sent_elsewhere,
            .takeFromOtherQuestion => {
                const qid = ret.take_from_other_question orelse return error.MissingQuestionId;
                response = .{ .take_from_other_question = qid };
            },
            .awaitFromThirdParty => response = .accept_from_third_party,
        }
        try ctx.callback(ctx.user_ctx, peer, response);
    }

    pub fn bootstrap(peer: *rpc.peer.Peer, user_ctx: *anyopaque, callback: BootstrapCallback) !u32 {
        const ctx = try peer.allocator.create(BootstrapContext);
        errdefer peer.allocator.destroy(ctx);
        ctx.* = .{ .user_ctx = user_ctx, .callback = callback };
        const question_id = try peer.sendBootstrap(ctx, bootstrapReturn);
        peer.setQuestionDeinitCtx(question_id, BootstrapContext.deinitCtx);
        return question_id;
    }

    pub const Server = struct {
        ctx: *anyopaque,
        vtable: VTable,
    };

    pub const VTable = struct {
        ping: Ping.Handler,
        ping_deferred: ?Ping.DeferredHandler = null,
    };

    pub fn exportServer(peer: *rpc.peer.Peer, server: *Server) !u32 {
        return peer.addExport(.{ .ctx = server, .on_call = onCall });
    }

    pub fn setBootstrap(peer: *rpc.peer.Peer, server: *Server) !u32 {
        return peer.setBootstrap(.{ .ctx = server, .on_call = onCall });
    }

    fn onCall(ctx: *anyopaque, peer: *rpc.peer.Peer, call: rpc.wire.protocol.Call, caps: *const rpc.caps.table.InboundCapTable) anyerror!void {
        const server: *Server = @ptrCast(@alignCast(ctx));
        switch (call.method_id) {
            Ping.ordinal => try Ping.handleCall(server, peer, call, caps),
            else => try peer.sendReturnException(call.question_id, "unknown method"),
        }
    }
    pub const PingParams = struct {
        pub const Reader = struct {
            _reader: message.StructReader,

            pub fn init(msg: *const message.Message) !Reader {
                const root = try msg.getRootStruct();
                return .{ ._reader = root };
            }

            pub fn wrap(reader: message.StructReader) Reader {
                return .{ ._reader = reader };
            }

            pub fn getCount(self: Reader) !u32 {
                return self._reader.readU32(0);
            }
        };

        pub const Builder = struct {
            _builder: message.StructBuilder,

            pub fn init(msg: *message.MessageBuilder) !Builder {
                const builder = try msg.allocateStruct(1, 0);
                return .{ ._builder = builder };
            }

            pub fn wrap(builder: message.StructBuilder) Builder {
                return .{ ._builder = builder };
            }

            pub fn setCount(self: *Builder, value: u32) !void {
                self._builder.writeU32(0, @bitCast(value));
            }
        };
    };

    pub const PingResults = struct {
        pub const Reader = struct {
            _reader: message.StructReader,

            pub fn init(msg: *const message.Message) !Reader {
                const root = try msg.getRootStruct();
                return .{ ._reader = root };
            }

            pub fn wrap(reader: message.StructReader) Reader {
                return .{ ._reader = reader };
            }

            pub fn getCount(self: Reader) !u32 {
                return self._reader.readU32(0);
            }
        };

        pub const Builder = struct {
            _builder: message.StructBuilder,

            pub fn init(msg: *message.MessageBuilder) !Builder {
                const builder = try msg.allocateStruct(1, 0);
                return .{ ._builder = builder };
            }

            pub fn wrap(builder: message.StructBuilder) Builder {
                return .{ ._builder = builder };
            }

            pub fn setCount(self: *Builder, value: u32) !void {
                self._builder.writeU32(0, @bitCast(value));
            }
        };
    };
};
