// Generated by capnpc-zig
// Source: all_types.capnp

const std = @import("std");
const capnpc = @import("capnpc-zig");
const message = capnpc.message;
const schema = capnpc.schema;

pub const CAPNP_SCHEMA_MANIFEST_JSON: []const u8 = "{\"schema\":\"all_types.capnp\",\"module\":\"all_types\",\"serde\":[{\"id\":14757395258967641089,\"type_name\":\"AllTypes\",\"to_json_export\":\"capnp_all_types_all_types_to_json\",\"from_json_export\":\"capnp_all_types_all_types_from_json\"}]}";
pub fn capnpSchemaManifestJson() []const u8 {
    return CAPNP_SCHEMA_MANIFEST_JSON;
}

pub const AllTypes = struct {
    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn getBoolField(self: Reader) !bool {
            return self._reader.readBool(0, 0);
        }

        pub fn getInt8Field(self: Reader) !i8 {
            return @bitCast(self._reader.readU8(1));
        }

        pub fn getInt16Field(self: Reader) !i16 {
            return @bitCast(self._reader.readU16(2));
        }

        pub fn getInt32Field(self: Reader) !i32 {
            return @bitCast(self._reader.readU32(4));
        }

        pub fn getInt64Field(self: Reader) !i64 {
            return @bitCast(self._reader.readU64(8));
        }

        pub fn getUint8Field(self: Reader) !u8 {
            return self._reader.readU8(2);
        }

        pub fn getUint16Field(self: Reader) !u16 {
            return self._reader.readU16(4);
        }

        pub fn getUint32Field(self: Reader) !u32 {
            return self._reader.readU32(8);
        }

        pub fn getUint64Field(self: Reader) !u64 {
            return self._reader.readU64(16);
        }

        pub fn getFloat32Field(self: Reader) !f32 {
            return @bitCast(self._reader.readU32(12));
        }

        pub fn getFloat64Field(self: Reader) !f64 {
            return @bitCast(self._reader.readU64(24));
        }

        pub fn getTextField(self: Reader) ![]const u8 {
            return try self._reader.readText(0);
        }

        pub fn getDataField(self: Reader) ![]const u8 {
            return try self._reader.readData(1);
        }

    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(4, 2);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn setBoolField(self: *Builder, value: bool) !void {
            self._builder.writeBool(0, 0, value);
        }

        pub fn setInt8Field(self: *Builder, value: i8) !void {
            self._builder.writeU8(1, @bitCast(value));
        }

        pub fn setInt16Field(self: *Builder, value: i16) !void {
            self._builder.writeU16(2, @bitCast(value));
        }

        pub fn setInt32Field(self: *Builder, value: i32) !void {
            self._builder.writeU32(4, @bitCast(value));
        }

        pub fn setInt64Field(self: *Builder, value: i64) !void {
            self._builder.writeU64(8, @bitCast(value));
        }

        pub fn setUint8Field(self: *Builder, value: u8) !void {
            self._builder.writeU8(2, @bitCast(value));
        }

        pub fn setUint16Field(self: *Builder, value: u16) !void {
            self._builder.writeU16(4, @bitCast(value));
        }

        pub fn setUint32Field(self: *Builder, value: u32) !void {
            self._builder.writeU32(8, @bitCast(value));
        }

        pub fn setUint64Field(self: *Builder, value: u64) !void {
            self._builder.writeU64(16, @bitCast(value));
        }

        pub fn setFloat32Field(self: *Builder, value: f32) !void {
            self._builder.writeU32(12, @bitCast(value));
        }

        pub fn setFloat64Field(self: *Builder, value: f64) !void {
            self._builder.writeU64(24, @bitCast(value));
        }

        pub fn setTextField(self: *Builder, value: []const u8) !void {
            try self._builder.writeText(0, value);
        }

        pub fn setDataField(self: *Builder, value: []const u8) !void {
            try self._builder.writeData(1, value);
        }

    };
};

