// Generated by capnpc-zig
// Source: defs.capnp

const std = @import("std");
const capnpc = @import("capnpc-zig");
const message = capnpc.message;
const schema = capnpc.schema;
const rpc = capnpc.rpc;

pub const CAPNP_SCHEMA_MANIFEST_JSON: []const u8 = "{\"schema\":\"defs.capnp\",\"module\":\"defs\",\"serde\":[]}";
pub fn capnpSchemaManifestJson() []const u8 {
    return CAPNP_SCHEMA_MANIFEST_JSON;
}

pub const version: u32 = @as(u32, 42);

pub const Status = enum(u16) {
    Active = 0,
    Inactive = 1,
    Pending = 2,
};
