// Generated by capnpc-zig
// Source: person.capnp

const std = @import("std");
// Resolving `capnpc` checks the runtime's codegen ABI, so a capnpc-zig
// plugin/runtime version skew fails here with one error.
const capnpc = capnpc_runtime: {
    const runtime = @import("capnpc-zig");
    const runtime_abi = if (@hasDecl(runtime, "codegen_abi")) runtime.codegen_abi.version else 0;
    if (runtime_abi < 1) @compileError(std.fmt.comptimePrint("capnpc-zig version skew: this file was generated for codegen ABI 1, which needs the capnpc-zig 0.19.0 runtime or newer, but the imported runtime provides ABI {d}. Upgrade the capnpc-zig dependency, or regenerate the file with the plugin that matches it.", .{runtime_abi}));
    if (runtime.codegen_abi.oldest_supported > 1) @compileError(std.fmt.comptimePrint("capnpc-zig version skew: this file was generated for codegen ABI 1, but the imported capnpc-zig runtime (ABI {d}) only supports ABI {d} and newer. Regenerate the file with the capnpc-zig {s} plugin or newer.", .{ runtime_abi, runtime.codegen_abi.oldest_supported, runtime.codegen_abi.release }));
    break :capnpc_runtime runtime;
};
const message = capnpc.message;
const schema = capnpc.schema;
const _capnp_file = @This();

pub const CAPNP_SCHEMA_MANIFEST_JSON: []const u8 = "{\"schema\":\"person.capnp\",\"module\":\"person\",\"serde\":[{\"id\":11651590505119481857,\"type_name\":\"Person\",\"to_json_export\":\"capnp_person_person_to_json\",\"from_json_export\":\"capnp_person_person_from_json\"}]}";
pub fn capnpSchemaManifestJson() []const u8 {
    return CAPNP_SCHEMA_MANIFEST_JSON;
}

pub const Person = struct {
    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn hasName(self: Reader) bool {
            return !self._reader.isPointerNull(0);
        }

        pub fn getName(self: Reader) ![]const u8 {
            return try self._reader.readTextStrict(0);
        }

        pub fn getAge(self: Reader) !u32 {
            return self._reader.readU32(0);
        }

        pub fn hasEmail(self: Reader) bool {
            return !self._reader.isPointerNull(1);
        }

        pub fn getEmail(self: Reader) ![]const u8 {
            return try self._reader.readTextStrict(1);
        }

    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(1, 2);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        /// Borrows storage at a stable address; any builder mutation invalidates the reader.
        pub fn asReader(self: @This(), storage: *capnpc.generated_helpers.ReaderStorage) !_capnp_file.Person.Reader {
            try storage.bind(self._builder.builder);
            try storage.message_view.validate(.{});
            return .{ ._reader = try storage.reader(self._builder) };
        }

        pub fn clearName(self: *@This()) message.BuildError!void {
            try (try self._builder.getAnyPointer(0)).setNull();
        }

        pub fn getName(self: @This()) ![]const u8 {
            var storage = capnpc.generated_helpers.ReaderStorage.init(self._builder.builder.allocator);
            defer storage.deinit();
            try storage.bind(self._builder.builder);
            const field_reader = try storage.reader(self._builder);
            return try field_reader.readTextStrict(0);
        }

        pub fn clearAge(self: *@This()) message.BuildError!void {
            self._builder.writeU32(0, 0);
        }

        pub fn getAge(self: @This()) !u32 {
            const field_reader = capnpc.generated_helpers.scalarReader(self._builder);
            return field_reader.readU32(0);
        }

        pub fn clearEmail(self: *@This()) message.BuildError!void {
            try (try self._builder.getAnyPointer(1)).setNull();
        }

        pub fn getEmail(self: @This()) ![]const u8 {
            var storage = capnpc.generated_helpers.ReaderStorage.init(self._builder.builder.allocator);
            defer storage.deinit();
            try storage.bind(self._builder.builder);
            const field_reader = try storage.reader(self._builder);
            return try field_reader.readTextStrict(1);
        }

        pub fn hasName(self: Builder) bool {
            return !self._builder.isPointerNull(0);
        }

        pub fn setName(self: *Builder, value: []const u8) message.BuildError!void {
            try self._builder.writeText(0, value);
        }

        pub fn setAge(self: *Builder, value: u32) message.BuildError!void {
            self._builder.writeU32(0, @bitCast(value));
        }

        pub fn hasEmail(self: Builder) bool {
            return !self._builder.isPointerNull(1);
        }

        pub fn setEmail(self: *Builder, value: []const u8) message.BuildError!void {
            try self._builder.writeText(1, value);
        }

    };
};

