// Generated by capnpc-zig
// Source: person.capnp

const std = @import("std");
const capnpc = @import("capnpc-zig");
const message = capnpc.message;
const schema = capnpc.schema;

pub const CAPNP_SCHEMA_MANIFEST_JSON: []const u8 = "{\"schema\":\"person.capnp\",\"module\":\"person\",\"serde\":[{\"id\":11651590505119481857,\"type_name\":\"Person\",\"to_json_export\":\"capnp_person_person_to_json\",\"from_json_export\":\"capnp_person_person_from_json\"}]}";
pub fn capnpSchemaManifestJson() []const u8 {
    return CAPNP_SCHEMA_MANIFEST_JSON;
}

pub const Person = struct {
    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn getName(self: Reader) ![]const u8 {
            return try self._reader.readText(0);
        }

        pub fn getAge(self: Reader) !u32 {
            return self._reader.readU32(0);
        }

        pub fn getEmail(self: Reader) ![]const u8 {
            return try self._reader.readText(1);
        }

    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(1, 2);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn setName(self: *Builder, value: []const u8) !void {
            try self._builder.writeText(0, value);
        }

        pub fn setAge(self: *Builder, value: u32) !void {
            self._builder.writeU32(0, @bitCast(value));
        }

        pub fn setEmail(self: *Builder, value: []const u8) !void {
            try self._builder.writeText(1, value);
        }

    };
};

