// Generated by capnpc-zig
// Source: person.capnp

const std = @import("std");
const capnpc = @import("capnpc-zig");
const message = capnpc.message;
const schema = capnpc.schema;

pub const CAPNP_SCHEMA_MANIFEST_JSON: []const u8 = "{\"schema\":\"person.capnp\",\"module\":\"person\",\"serde\":[{\"id\":11651590505119481857,\"type_name\":\"Person\",\"to_json_export\":\"capnp_person_person_to_json\",\"from_json_export\":\"capnp_person_person_from_json\"}]}";
pub fn capnpSchemaManifestJson() []const u8 {
    return CAPNP_SCHEMA_MANIFEST_JSON;
}

pub const Person = struct {
    fn EnumListReader(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !EnumType {
                return std.meta.intToEnum(EnumType, try self._list.get(index)) catch return error.InvalidEnumValue;
            }

            pub fn raw(self: @This()) message.U16ListReader {
                return self._list;
            }
        };
    }

    fn EnumListBuilder(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn set(self: @This(), index: u32, value: EnumType) !void {
                try self._list.set(index, @intFromEnum(value));
            }

            pub fn raw(self: @This()) message.U16ListBuilder {
                return self._list;
            }
        };
    }

    fn StructListReader(comptime StructType: type) type {
        return struct {
            _list: message.StructListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Reader {
                const item = try self._list.get(index);
                return StructType.Reader.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListReader {
                return self._list;
            }
        };
    }

    fn StructListBuilder(comptime StructType: type) type {
        return struct {
            _list: message.StructListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Builder {
                const item = try self._list.get(index);
                return StructType.Builder.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListBuilder {
                return self._list;
            }
        };
    }

    const DataListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) ![]const u8 {
            return try self._list.getData(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const DataListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, value: []const u8) !void {
            try self._list.setData(index, value);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    const CapabilityListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) !message.Capability {
            return try self._list.getCapability(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const CapabilityListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, cap: message.Capability) !void {
            try self._list.setCapability(index, cap);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn getName(self: Reader) ![]const u8 {
            return try self._reader.readText(0);
        }

        pub fn getAge(self: Reader) !u32 {
            return self._reader.readU32(0);
        }

        pub fn getEmail(self: Reader) ![]const u8 {
            return try self._reader.readText(1);
        }

    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(1, 2);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn setName(self: *Builder, value: []const u8) !void {
            try self._builder.writeText(0, value);
        }

        pub fn setAge(self: *Builder, value: u32) !void {
            self._builder.writeU32(0, @bitCast(value));
        }

        pub fn setEmail(self: *Builder, value: []const u8) !void {
            try self._builder.writeText(1, value);
        }

    };
};

