// Generated by capnpc-zig
// Source: shape.capnp

const std = @import("std");
const capnpc = @import("capnpc-zig");
const message = capnpc.message;
const schema = capnpc.schema;

pub const CAPNP_SCHEMA_MANIFEST_JSON: []const u8 = "{\"schema\":\"shape.capnp\",\"module\":\"shape\",\"serde\":[{\"id\":13527612320720337666,\"type_name\":\"Shape\",\"to_json_export\":\"capnp_shape_shape_to_json\",\"from_json_export\":\"capnp_shape_shape_from_json\"}]}";
pub fn capnpSchemaManifestJson() []const u8 {
    return CAPNP_SCHEMA_MANIFEST_JSON;
}

pub const Color = enum(u16) {
    Red = 0,
    Green = 1,
    Blue = 2,
};

pub const Shape = struct {
    const EnumListReader = message.typed_list_helpers.EnumListReader;
    const EnumListBuilder = message.typed_list_helpers.EnumListBuilder;
    const StructListReader = message.typed_list_helpers.StructListReader;
    const StructListBuilder = message.typed_list_helpers.StructListBuilder;
    const DataListReader = message.typed_list_helpers.DataListReader;
    const DataListBuilder = message.typed_list_helpers.DataListBuilder;
    const CapabilityListReader = message.typed_list_helpers.CapabilityListReader;
    const CapabilityListBuilder = message.typed_list_helpers.CapabilityListBuilder;

    pub const WhichTag = enum(u16) {
        circle = 0,
        rectangle = 1,
    };

    pub const Rectangle = struct {
        pub const Reader = struct {
            _reader: message.StructReader,

            pub fn wrap(reader: message.StructReader) Reader {
                return .{ ._reader = reader };
            }

            pub fn getWidth(self: Reader) !f32 {
                return @bitCast(self._reader.readU32(4));
            }

            pub fn getHeight(self: Reader) !f32 {
                return @bitCast(self._reader.readU32(8));
            }

        };

        pub const Builder = struct {
            _builder: message.StructBuilder,

            pub fn wrap(builder: message.StructBuilder) Builder {
                return .{ ._builder = builder };
            }

            pub fn setWidth(self: *Builder, value: f32) !void {
                self._builder.writeU32(4, @bitCast(value));
            }

            pub fn setHeight(self: *Builder, value: f32) !void {
                self._builder.writeU32(8, @bitCast(value));
            }

        };
    };

    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn which(self: Reader) error{InvalidEnumValue}!WhichTag {
            return std.meta.intToEnum(WhichTag, self._reader.readU16(2)) catch return error.InvalidEnumValue;
        }

        pub fn getColor(self: Reader) !Color {
            return std.meta.intToEnum(Color, self._reader.readU16(0)) catch return error.InvalidEnumValue;
        }

        pub fn getCircle(self: Reader) !f64 {
            return @bitCast(self._reader.readU64(8));
        }

        pub fn getRectangle(self: Reader) Rectangle.Reader {
            return .{ ._reader = self._reader };
        }

    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(2, 0);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn setColor(self: *Builder, value: Color) !void {
            self._builder.writeU16(0, @as(u16, @intFromEnum(value)));
        }

        pub fn setCircle(self: *Builder, value: f64) !void {
            self._builder.writeU16(2, 0);
            self._builder.writeU64(8, @bitCast(value));
        }

        pub fn initRectangle(self: *Builder) Rectangle.Builder {
            self._builder.writeU16(2, 1);
            return .{ ._builder = self._builder };
        }

    };
};

