// Generated by capnpc-zig
// Source: shape.capnp

const std = @import("std");
const capnpc = @import("capnpc-zig");
const message = capnpc.message;
const schema = capnpc.schema;
const rpc = capnpc.rpc;

pub const CAPNP_SCHEMA_MANIFEST_JSON: []const u8 = "{\"schema\":\"shape.capnp\",\"module\":\"shape\",\"serde\":[{\"id\":13527612320720337666,\"type_name\":\"Shape\",\"to_json_export\":\"capnp_shape_shape_to_json\",\"from_json_export\":\"capnp_shape_shape_from_json\"}]}";
pub fn capnpSchemaManifestJson() []const u8 {
    return CAPNP_SCHEMA_MANIFEST_JSON;
}

pub const Color = enum(u16) {
    Red = 0,
    Green = 1,
    Blue = 2,
};

pub const Shape = struct {
    fn EnumListReader(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !EnumType {
                return @enumFromInt(try self._list.get(index));
            }

            pub fn raw(self: @This()) message.U16ListReader {
                return self._list;
            }
        };
    }

    fn EnumListBuilder(comptime EnumType: type) type {
        return struct {
            _list: message.U16ListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn set(self: @This(), index: u32, value: EnumType) !void {
                try self._list.set(index, @intFromEnum(value));
            }

            pub fn raw(self: @This()) message.U16ListBuilder {
                return self._list;
            }
        };
    }

    fn StructListReader(comptime StructType: type) type {
        return struct {
            _list: message.StructListReader,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Reader {
                const item = try self._list.get(index);
                return StructType.Reader.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListReader {
                return self._list;
            }
        };
    }

    fn StructListBuilder(comptime StructType: type) type {
        return struct {
            _list: message.StructListBuilder,

            pub fn len(self: @This()) u32 {
                return self._list.len();
            }

            pub fn get(self: @This(), index: u32) !StructType.Builder {
                const item = try self._list.get(index);
                return StructType.Builder.wrap(item);
            }

            pub fn raw(self: @This()) message.StructListBuilder {
                return self._list;
            }
        };
    }

    const DataListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) ![]const u8 {
            return try self._list.getData(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const DataListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, value: []const u8) !void {
            try self._list.setData(index, value);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    const CapabilityListReader = struct {
        _list: message.PointerListReader,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn get(self: @This(), index: u32) !message.Capability {
            return try self._list.getCapability(index);
        }

        pub fn raw(self: @This()) message.PointerListReader {
            return self._list;
        }
    };

    const CapabilityListBuilder = struct {
        _list: message.PointerListBuilder,

        pub fn len(self: @This()) u32 {
            return self._list.len();
        }

        pub fn set(self: @This(), index: u32, cap: message.Capability) !void {
            try self._list.setCapability(index, cap);
        }

        pub fn setNull(self: @This(), index: u32) !void {
            try self._list.setNull(index);
        }

        pub fn raw(self: @This()) message.PointerListBuilder {
            return self._list;
        }
    };

    pub const WhichTag = enum(u16) {
        circle = 0,
        rectangle = 1,
    };

    pub const Rectangle = struct {
        pub const Reader = struct {
            _reader: message.StructReader,

            pub fn wrap(_reader: message.StructReader) Reader {
                return .{ ._reader = _reader };
            }

            pub fn getWidth(self: Reader) !f32 {
                return @bitCast(self._reader.readU32(4));
            }

            pub fn getHeight(self: Reader) !f32 {
                return @bitCast(self._reader.readU32(8));
            }
        };

        pub const Builder = struct {
            _builder: message.StructBuilder,

            pub fn wrap(_builder: message.StructBuilder) Builder {
                return .{ ._builder = _builder };
            }

            pub fn setWidth(self: *Builder, value: f32) !void {
                self._builder.writeU32(4, @bitCast(value));
            }

            pub fn setHeight(self: *Builder, value: f32) !void {
                self._builder.writeU32(8, @bitCast(value));
            }
        };
    };

    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn which(self: Reader) WhichTag {
            return @enumFromInt(self._reader.readU16(2));
        }

        pub fn getColor(self: Reader) !Color {
            return @enumFromInt(self._reader.readU16(0));
        }

        pub fn getCircle(self: Reader) !f64 {
            return @bitCast(self._reader.readU64(8));
        }

        pub fn getRectangle(self: Reader) Rectangle.Reader {
            return .{ ._reader = self._reader };
        }
    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(2, 0);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn setColor(self: *Builder, value: Color) !void {
            self._builder.writeU16(0, @as(u16, @intFromEnum(value)));
        }

        pub fn setCircle(self: *Builder, value: f64) !void {
            self._builder.writeU16(2, 0);
            self._builder.writeU64(8, @bitCast(value));
        }

        pub fn initRectangle(self: *Builder) Rectangle.Builder {
            self._builder.writeU16(2, 1);
            return .{ ._builder = self._builder };
        }
    };
};
