//! Public API snapshot tool.
//!
//! Walks the library's `pub` declaration tree at comptime and emits a
//! sorted, line-oriented description of the API surface: declaration paths
//! plus type/function signatures. The checked-in snapshot
//! (docs/api-snapshot.txt) is the reviewed public surface; `zig build
//! check-api` fails when the live surface drifts from it, making API
//! changes an explicit, reviewable act:
//!
//!   zig build api-snapshot   # regenerate docs/api-snapshot.txt
//!   zig build check-api      # diff live surface against the snapshot
//!
//! Stability tiers for individual modules live in docs/stability.md; this
//! gate makes sure no change to any tier lands unnoticed.

const std = @import("std");
const capnpc = @import("capnpc-zig");

const max_depth = 6;

fn isContainer(comptime T: type) bool {
    return switch (@typeInfo(T)) {
        .@"struct", .@"enum", .@"union", .@"opaque" => true,
        else => false,
    };
}

fn containerKind(comptime T: type) []const u8 {
    return switch (@typeInfo(T)) {
        .@"struct" => "struct",
        .@"enum" => "enum",
        .@"union" => "union",
        .@"opaque" => "opaque",
        else => unreachable,
    };
}

/// Skip recursing into types that are not ours (std re-exports etc.).
fn foreignType(comptime T: type) bool {
    const name = @typeName(T);
    return std.mem.startsWith(u8, name, "std.") or
        std.mem.startsWith(u8, name, "builtin.") or
        std.mem.eql(u8, name, "std") or
        std.mem.eql(u8, name, "builtin");
}

fn contains(comptime seen: []const type, comptime T: type) bool {
    for (seen) |S| {
        if (S == T) return true;
    }
    return false;
}

fn walk(
    comptime T: type,
    comptime path: []const u8,
    comptime depth: usize,
    comptime seen: *[]const type,
    comptime lines: *[]const []const u8,
) void {
    if (depth >= max_depth) return;
    if (contains(seen.*, T)) return;
    seen.* = seen.* ++ [_]type{T};

    for (std.meta.declarations(T)) |decl_name| {
        const decl_path = path ++ "." ++ decl_name;
        const D = @field(T, decl_name);
        const DType = @TypeOf(D);

        if (DType == type) {
            if (isContainer(D)) {
                lines.* = lines.* ++ [_][]const u8{decl_path ++ ": " ++ containerKind(D)};
                if (!foreignType(D)) {
                    walk(D, decl_path, depth + 1, seen, lines);
                }
            } else {
                lines.* = lines.* ++ [_][]const u8{decl_path ++ ": type = " ++ @typeName(D)};
            }
        } else if (@typeInfo(DType) == .@"fn") {
            lines.* = lines.* ++ [_][]const u8{decl_path ++ ": " ++ @typeName(DType)};
        } else {
            lines.* = lines.* ++ [_][]const u8{decl_path ++ ": const " ++ @typeName(DType)};
        }
    }
}

const api_lines: []const []const u8 = blk: {
    @setEvalBranchQuota(20_000_000);
    var seen: []const type = &.{};
    var lines: []const []const u8 = &.{};
    walk(capnpc, "capnpc-zig", 0, &seen, &lines);
    break :blk lines;
};

fn lessThan(_: void, a: []const u8, b: []const u8) bool {
    return std.mem.lessThan(u8, a, b);
}

/// Copy `line` with every `__struct_<digits>` collapsed to `__struct_*`.
/// Those suffixes are compiler-assigned anonymous-type counters: they shift
/// whenever unrelated code changes and differ between targets, so keeping
/// them verbatim would make the snapshot churn without any API change.
fn normalizeLine(allocator: std.mem.Allocator, line: []const u8) ![]u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(allocator);
    const marker = "__struct_";
    var rest = line;
    while (std.mem.indexOf(u8, rest, marker)) |idx| {
        var end = idx + marker.len;
        while (end < rest.len and std.ascii.isDigit(rest[end])) end += 1;
        try out.appendSlice(allocator, rest[0 .. idx + marker.len]);
        try out.append(allocator, '*');
        rest = rest[end..];
    }
    try out.appendSlice(allocator, rest);
    return out.toOwnedSlice(allocator);
}

fn renderSnapshot(allocator: std.mem.Allocator) ![]u8 {
    const normalized = try allocator.alloc([]u8, api_lines.len);
    var normalized_count: usize = 0;
    defer {
        for (normalized[0..normalized_count]) |line| allocator.free(line);
        allocator.free(normalized);
    }
    for (api_lines) |line| {
        normalized[normalized_count] = try normalizeLine(allocator, line);
        normalized_count += 1;
    }
    std.mem.sort([]u8, normalized, {}, lessThan);

    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(allocator);
    try out.appendSlice(allocator,
        \\# Public API snapshot — generated by `zig build api-snapshot`.
        \\# A diff here is an API change: review it against docs/stability.md
        \\# and commit the regenerated file deliberately.
        \\
    );
    for (normalized) |line| {
        try out.appendSlice(allocator, line);
        try out.append(allocator, '\n');
    }
    return out.toOwnedSlice(allocator);
}

pub fn main(init: std.process.Init) !void {
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();
    const io = init.io;

    var mode: enum { check, write } = .check;
    var snapshot_path: []const u8 = "docs/api-snapshot.txt";

    var iter = std.process.Args.Iterator.init(init.minimal.args);
    _ = iter.skip();
    while (iter.next()) |arg| {
        if (std.mem.eql(u8, arg, "--write")) {
            mode = .write;
        } else if (std.mem.eql(u8, arg, "--check")) {
            mode = .check;
        } else if (std.mem.eql(u8, arg, "--path")) {
            snapshot_path = iter.next() orelse return error.InvalidArgument;
        } else {
            std.debug.print("api-snapshot: unknown argument: {s}\n", .{arg});
            return error.InvalidArgument;
        }
    }

    const rendered = try renderSnapshot(allocator);
    defer allocator.free(rendered);

    switch (mode) {
        .write => {
            var file = try std.Io.Dir.cwd().createFile(io, snapshot_path, .{});
            defer file.close(io);
            try file.writeStreamingAll(io, rendered);
            std.debug.print("api-snapshot: wrote {} lines to {s}\n", .{ api_lines.len, snapshot_path });
        },
        .check => {
            const existing = std.Io.Dir.cwd().readFileAlloc(io, snapshot_path, allocator, .limited(16 * 1024 * 1024)) catch |err| {
                std.debug.print(
                    "api-snapshot: cannot read {s} ({}); run `zig build api-snapshot` to create it\n",
                    .{ snapshot_path, err },
                );
                return error.ApiSnapshotMissing;
            };
            defer allocator.free(existing);

            if (std.mem.eql(u8, existing, rendered)) {
                std.debug.print("api-snapshot: OK ({} declarations)\n", .{api_lines.len});
                return;
            }

            // Print a first-divergence hint rather than a full diff.
            var existing_it = std.mem.splitScalar(u8, existing, '\n');
            var rendered_it = std.mem.splitScalar(u8, rendered, '\n');
            var line_no: usize = 1;
            while (true) : (line_no += 1) {
                const a = existing_it.next();
                const b = rendered_it.next();
                if (a == null and b == null) break;
                const a_line = a orelse "<end of snapshot>";
                const b_line = b orelse "<end of live surface>";
                if (!std.mem.eql(u8, a_line, b_line)) {
                    std.debug.print(
                        "api-snapshot: drift at line {}:\n  snapshot: {s}\n  live:     {s}\n",
                        .{ line_no, a_line, b_line },
                    );
                    break;
                }
            }
            std.debug.print(
                "api-snapshot: public API surface changed. Review against docs/stability.md, then run `zig build api-snapshot` and commit the result.\n",
                .{},
            );
            return error.ApiSnapshotDrift;
        },
    }
}
